//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ws_recepcaolote
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sped.fazenda.gov.br/", ConfigurationName="ws_recepcaolote.RecepcaoLoteReinf")]
    public interface RecepcaoLoteReinf
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sped.fazenda.gov.br/RecepcaoLoteReinf/ReceberLoteEventos", ReplyAction="http://sped.fazenda.gov.br/RecepcaoLoteReinf/ReceberLoteEventosResponse")]
        ws_recepcaolote.ReceberLoteEventosResponse ReceberLoteEventos(ws_recepcaolote.ReceberLoteEventosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sped.fazenda.gov.br/RecepcaoLoteReinf/ReceberLoteEventos", ReplyAction="http://sped.fazenda.gov.br/RecepcaoLoteReinf/ReceberLoteEventosResponse")]
        System.Threading.Tasks.Task<ws_recepcaolote.ReceberLoteEventosResponse> ReceberLoteEventosAsync(ws_recepcaolote.ReceberLoteEventosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReceberLoteEventosRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReceberLoteEventos", Namespace="http://sped.fazenda.gov.br/", Order=0)]
        public ws_recepcaolote.ReceberLoteEventosRequestBody Body;
        
        public ReceberLoteEventosRequest()
        {
        }
        
        public ReceberLoteEventosRequest(ws_recepcaolote.ReceberLoteEventosRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sped.fazenda.gov.br/")]
    public partial class ReceberLoteEventosRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement loteEventos;
        
        public ReceberLoteEventosRequestBody()
        {
        }
        
        public ReceberLoteEventosRequestBody(System.Xml.XmlElement loteEventos)
        {
            this.loteEventos = loteEventos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReceberLoteEventosResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReceberLoteEventosResponse", Namespace="http://sped.fazenda.gov.br/", Order=0)]
        public ws_recepcaolote.ReceberLoteEventosResponseBody Body;
        
        public ReceberLoteEventosResponse()
        {
        }
        
        public ReceberLoteEventosResponse(ws_recepcaolote.ReceberLoteEventosResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sped.fazenda.gov.br/")]
    public partial class ReceberLoteEventosResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement ReceberLoteEventosResult;
        
        public ReceberLoteEventosResponseBody()
        {
        }
        
        public ReceberLoteEventosResponseBody(System.Xml.XmlElement ReceberLoteEventosResult)
        {
            this.ReceberLoteEventosResult = ReceberLoteEventosResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface RecepcaoLoteReinfChannel : ws_recepcaolote.RecepcaoLoteReinf, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class RecepcaoLoteReinfClient : System.ServiceModel.ClientBase<ws_recepcaolote.RecepcaoLoteReinf>, ws_recepcaolote.RecepcaoLoteReinf
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public RecepcaoLoteReinfClient() : 
                base(RecepcaoLoteReinfClient.GetDefaultBinding(), RecepcaoLoteReinfClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_RecepcaoLoteReinf.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RecepcaoLoteReinfClient(EndpointConfiguration endpointConfiguration) : 
                base(RecepcaoLoteReinfClient.GetBindingForEndpoint(endpointConfiguration), RecepcaoLoteReinfClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RecepcaoLoteReinfClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(RecepcaoLoteReinfClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RecepcaoLoteReinfClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(RecepcaoLoteReinfClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RecepcaoLoteReinfClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ws_recepcaolote.ReceberLoteEventosResponse ReceberLoteEventos(ws_recepcaolote.ReceberLoteEventosRequest request)
        {
            return base.Channel.ReceberLoteEventos(request);
        }
        
        public System.Threading.Tasks.Task<ws_recepcaolote.ReceberLoteEventosResponse> ReceberLoteEventosAsync(ws_recepcaolote.ReceberLoteEventosRequest request)
        {
            return base.Channel.ReceberLoteEventosAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_RecepcaoLoteReinf))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_RecepcaoLoteReinf))
            {
                return new System.ServiceModel.EndpointAddress("https://reinf.receita.fazenda.gov.br/WsREINF/RecepcaoLoteReinf.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return RecepcaoLoteReinfClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_RecepcaoLoteReinf);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return RecepcaoLoteReinfClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_RecepcaoLoteReinf);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_RecepcaoLoteReinf,
        }
    }
}
