//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ws_osasco
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestBase", Namespace="http://schemas.datacontract.org/2004/07/Eissnfe.Negocio.WebServices.Mensagem")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ws_osasco.CancelamentoNotaFiscalRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ws_osasco.EmissaoNotaFiscalLoteRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ws_osasco.ConsultaNotaFiscalLoteRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ws_osasco.ConsultaNotaFiscalRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ws_osasco.EmissaoNotaFiscalRequest))]
    public partial class RequestBase : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CancelamentoNotaFiscalRequest", Namespace="http://schemas.datacontract.org/2004/07/Eissnfe.Negocio.WebServices.Mensagem")]
    public partial class CancelamentoNotaFiscalRequest : ws_osasco.RequestBase
    {
        
        private string ChaveAutenticacaoField;
        
        private bool HomologacaoField;
        
        private string NumeroNotaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChaveAutenticacao
        {
            get
            {
                return this.ChaveAutenticacaoField;
            }
            set
            {
                this.ChaveAutenticacaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Homologacao
        {
            get
            {
                return this.HomologacaoField;
            }
            set
            {
                this.HomologacaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroNota
        {
            get
            {
                return this.NumeroNotaField;
            }
            set
            {
                this.NumeroNotaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmissaoNotaFiscalLoteRequest", Namespace="http://schemas.datacontract.org/2004/07/Eissnfe.Negocio.WebServices.Mensagem")]
    public partial class EmissaoNotaFiscalLoteRequest : ws_osasco.RequestBase
    {
        
        private ws_osasco.NotasFiscaisLoteDTO NotasField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ws_osasco.NotasFiscaisLoteDTO Notas
        {
            get
            {
                return this.NotasField;
            }
            set
            {
                this.NotasField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsultaNotaFiscalLoteRequest", Namespace="http://schemas.datacontract.org/2004/07/Eissnfe.Negocio.WebServices.Mensagem")]
    public partial class ConsultaNotaFiscalLoteRequest : ws_osasco.RequestBase
    {
        
        private string ChaveAutenticacaoField;
        
        private int CodigoLoteField;
        
        private string StatusNotasField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChaveAutenticacao
        {
            get
            {
                return this.ChaveAutenticacaoField;
            }
            set
            {
                this.ChaveAutenticacaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoLote
        {
            get
            {
                return this.CodigoLoteField;
            }
            set
            {
                this.CodigoLoteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusNotas
        {
            get
            {
                return this.StatusNotasField;
            }
            set
            {
                this.StatusNotasField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsultaNotaFiscalRequest", Namespace="http://schemas.datacontract.org/2004/07/Eissnfe.Negocio.WebServices.Mensagem")]
    public partial class ConsultaNotaFiscalRequest : ws_osasco.RequestBase
    {
        
        private string ChaveAutenticacaoField;
        
        private System.Nullable<System.DateTime> DataFinalField;
        
        private System.Nullable<System.DateTime> DataInicialField;
        
        private System.Nullable<decimal> NumeroReciboFinalField;
        
        private System.Nullable<decimal> NumeroReciboInicialField;
        
        private System.Nullable<decimal> NumeroReciboUnicoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChaveAutenticacao
        {
            get
            {
                return this.ChaveAutenticacaoField;
            }
            set
            {
                this.ChaveAutenticacaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataFinal
        {
            get
            {
                return this.DataFinalField;
            }
            set
            {
                this.DataFinalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataInicial
        {
            get
            {
                return this.DataInicialField;
            }
            set
            {
                this.DataInicialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> NumeroReciboFinal
        {
            get
            {
                return this.NumeroReciboFinalField;
            }
            set
            {
                this.NumeroReciboFinalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> NumeroReciboInicial
        {
            get
            {
                return this.NumeroReciboInicialField;
            }
            set
            {
                this.NumeroReciboInicialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> NumeroReciboUnico
        {
            get
            {
                return this.NumeroReciboUnicoField;
            }
            set
            {
                this.NumeroReciboUnicoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmissaoNotaFiscalRequest", Namespace="http://schemas.datacontract.org/2004/07/Eissnfe.Negocio.WebServices.Mensagem")]
    public partial class EmissaoNotaFiscalRequest : ws_osasco.RequestBase
    {
        
        private ws_osasco.NotaFiscalDTO NotaFiscalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ws_osasco.NotaFiscalDTO NotaFiscal
        {
            get
            {
                return this.NotaFiscalField;
            }
            set
            {
                this.NotaFiscalField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NotaFiscalDTO", Namespace="http://schemas.datacontract.org/2004/07/Eissnfe.Dominio.DataTransferObject.Presta" +
        "dor")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ws_osasco.NotaFiscalLoteDTO))]
    public partial class NotaFiscalDTO : object
    {
        
        private System.Nullable<decimal> AliquotaField;
        
        private string AtividadeField;
        
        private string CEPPrestacaoServicoField;
        
        private string ChaveAutenticacaoField;
        
        private string CidadePrestacaoServicoField;
        
        private string CodObraField;
        
        private System.Nullable<System.DateTime> DataReciboField;
        
        private string EnderecoPrestacaoServicoField;
        
        private string EqptoReciboField;
        
        private string EstadoPrestacaoServicoField;
        
        private bool HomologacaoField;
        
        private string InformacoesAdicionaisField;
        
        private System.Nullable<decimal> NotaSubstituidaField;
        
        private bool NotificarTomadorPorEmailField;
        
        private string NumeroCDCField;
        
        private string NumeroCeiField;
        
        private System.Nullable<decimal> NumeroReciboField;
        
        private bool SemIncidenciaISSField;
        
        private bool SimplesNacionalField;
        
        private bool SubstituicaoTributariaField;
        
        private ws_osasco.PessoaDTO TomadorField;
        
        private bool TomadorEstrangeiroField;
        
        private decimal ValorField;
        
        private System.Nullable<decimal> ValorCSLLField;
        
        private System.Nullable<decimal> ValorCofinsField;
        
        private System.Nullable<decimal> ValorDeducaoField;
        
        private System.Nullable<decimal> ValorINSSField;
        
        private System.Nullable<decimal> ValorIRField;
        
        private System.Nullable<decimal> ValorOutrosImpostosField;
        
        private System.Nullable<decimal> ValorPisPasepField;
        
        private System.Nullable<decimal> ValorRepasseField;
        
        private string ipUsuarioEmissorField;
        
        private System.Nullable<int> nrExercicioReferenciaField;
        
        private System.Nullable<int> nrMesReferenciaField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<decimal> Aliquota
        {
            get
            {
                return this.AliquotaField;
            }
            set
            {
                this.AliquotaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Atividade
        {
            get
            {
                return this.AtividadeField;
            }
            set
            {
                this.AtividadeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CEPPrestacaoServico
        {
            get
            {
                return this.CEPPrestacaoServicoField;
            }
            set
            {
                this.CEPPrestacaoServicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChaveAutenticacao
        {
            get
            {
                return this.ChaveAutenticacaoField;
            }
            set
            {
                this.ChaveAutenticacaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CidadePrestacaoServico
        {
            get
            {
                return this.CidadePrestacaoServicoField;
            }
            set
            {
                this.CidadePrestacaoServicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodObra
        {
            get
            {
                return this.CodObraField;
            }
            set
            {
                this.CodObraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataRecibo
        {
            get
            {
                return this.DataReciboField;
            }
            set
            {
                this.DataReciboField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnderecoPrestacaoServico
        {
            get
            {
                return this.EnderecoPrestacaoServicoField;
            }
            set
            {
                this.EnderecoPrestacaoServicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EqptoRecibo
        {
            get
            {
                return this.EqptoReciboField;
            }
            set
            {
                this.EqptoReciboField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoPrestacaoServico
        {
            get
            {
                return this.EstadoPrestacaoServicoField;
            }
            set
            {
                this.EstadoPrestacaoServicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Homologacao
        {
            get
            {
                return this.HomologacaoField;
            }
            set
            {
                this.HomologacaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InformacoesAdicionais
        {
            get
            {
                return this.InformacoesAdicionaisField;
            }
            set
            {
                this.InformacoesAdicionaisField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> NotaSubstituida
        {
            get
            {
                return this.NotaSubstituidaField;
            }
            set
            {
                this.NotaSubstituidaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool NotificarTomadorPorEmail
        {
            get
            {
                return this.NotificarTomadorPorEmailField;
            }
            set
            {
                this.NotificarTomadorPorEmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroCDC
        {
            get
            {
                return this.NumeroCDCField;
            }
            set
            {
                this.NumeroCDCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroCei
        {
            get
            {
                return this.NumeroCeiField;
            }
            set
            {
                this.NumeroCeiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> NumeroRecibo
        {
            get
            {
                return this.NumeroReciboField;
            }
            set
            {
                this.NumeroReciboField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SemIncidenciaISS
        {
            get
            {
                return this.SemIncidenciaISSField;
            }
            set
            {
                this.SemIncidenciaISSField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SimplesNacional
        {
            get
            {
                return this.SimplesNacionalField;
            }
            set
            {
                this.SimplesNacionalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool SubstituicaoTributaria
        {
            get
            {
                return this.SubstituicaoTributariaField;
            }
            set
            {
                this.SubstituicaoTributariaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ws_osasco.PessoaDTO Tomador
        {
            get
            {
                return this.TomadorField;
            }
            set
            {
                this.TomadorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TomadorEstrangeiro
        {
            get
            {
                return this.TomadorEstrangeiroField;
            }
            set
            {
                this.TomadorEstrangeiroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal Valor
        {
            get
            {
                return this.ValorField;
            }
            set
            {
                this.ValorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ValorCSLL
        {
            get
            {
                return this.ValorCSLLField;
            }
            set
            {
                this.ValorCSLLField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ValorCofins
        {
            get
            {
                return this.ValorCofinsField;
            }
            set
            {
                this.ValorCofinsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<decimal> ValorDeducao
        {
            get
            {
                return this.ValorDeducaoField;
            }
            set
            {
                this.ValorDeducaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ValorINSS
        {
            get
            {
                return this.ValorINSSField;
            }
            set
            {
                this.ValorINSSField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ValorIR
        {
            get
            {
                return this.ValorIRField;
            }
            set
            {
                this.ValorIRField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ValorOutrosImpostos
        {
            get
            {
                return this.ValorOutrosImpostosField;
            }
            set
            {
                this.ValorOutrosImpostosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ValorPisPasep
        {
            get
            {
                return this.ValorPisPasepField;
            }
            set
            {
                this.ValorPisPasepField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ValorRepasse
        {
            get
            {
                return this.ValorRepasseField;
            }
            set
            {
                this.ValorRepasseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ipUsuarioEmissor
        {
            get
            {
                return this.ipUsuarioEmissorField;
            }
            set
            {
                this.ipUsuarioEmissorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> nrExercicioReferencia
        {
            get
            {
                return this.nrExercicioReferenciaField;
            }
            set
            {
                this.nrExercicioReferenciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> nrMesReferencia
        {
            get
            {
                return this.nrMesReferenciaField;
            }
            set
            {
                this.nrMesReferenciaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NotasFiscaisLoteDTO", Namespace="http://schemas.datacontract.org/2004/07/Eissnfe.Dominio.DataTransferObject.Presta" +
        "dor")]
    public partial class NotasFiscaisLoteDTO : object
    {
        
        private string ChaveAutenticacaoField;
        
        private string EmailContatoField;
        
        private ws_osasco.NotaFiscalLoteDTO[] NotasField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ChaveAutenticacao
        {
            get
            {
                return this.ChaveAutenticacaoField;
            }
            set
            {
                this.ChaveAutenticacaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string EmailContato
        {
            get
            {
                return this.EmailContatoField;
            }
            set
            {
                this.EmailContatoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ws_osasco.NotaFiscalLoteDTO[] Notas
        {
            get
            {
                return this.NotasField;
            }
            set
            {
                this.NotasField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NotaFiscalLoteDTO", Namespace="http://schemas.datacontract.org/2004/07/Eissnfe.Dominio.DataTransferObject.Presta" +
        "dor")]
    public partial class NotaFiscalLoteDTO : ws_osasco.NotaFiscalDTO
    {
        
        private string IdentificadorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identificador
        {
            get
            {
                return this.IdentificadorField;
            }
            set
            {
                this.IdentificadorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PessoaDTO", Namespace="http://schemas.datacontract.org/2004/07/Eissnfe.Dominio.DataTransferObject.Contri" +
        "buinte")]
    public partial class PessoaDTO : object
    {
        
        private string CNPJField;
        
        private string CPFField;
        
        private string DDDField;
        
        private string EmailField;
        
        private ws_osasco.EnderecoDTO EnderecoField;
        
        private string InscricaoMunicipalField;
        
        private string NomeField;
        
        private string NomeFantasiaField;
        
        private string RazaoSocialField;
        
        private string TelefoneField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CNPJ
        {
            get
            {
                return this.CNPJField;
            }
            set
            {
                this.CNPJField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CPF
        {
            get
            {
                return this.CPFField;
            }
            set
            {
                this.CPFField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DDD
        {
            get
            {
                return this.DDDField;
            }
            set
            {
                this.DDDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ws_osasco.EnderecoDTO Endereco
        {
            get
            {
                return this.EnderecoField;
            }
            set
            {
                this.EnderecoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InscricaoMunicipal
        {
            get
            {
                return this.InscricaoMunicipalField;
            }
            set
            {
                this.InscricaoMunicipalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome
        {
            get
            {
                return this.NomeField;
            }
            set
            {
                this.NomeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeFantasia
        {
            get
            {
                return this.NomeFantasiaField;
            }
            set
            {
                this.NomeFantasiaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RazaoSocial
        {
            get
            {
                return this.RazaoSocialField;
            }
            set
            {
                this.RazaoSocialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefone
        {
            get
            {
                return this.TelefoneField;
            }
            set
            {
                this.TelefoneField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnderecoDTO", Namespace="http://schemas.datacontract.org/2004/07/Eissnfe.Dominio.DataTransferObject.Contri" +
        "buinte")]
    public partial class EnderecoDTO : object
    {
        
        private string BairroField;
        
        private string CEPField;
        
        private string CidadeField;
        
        private string ComplementoField;
        
        private string EstadoField;
        
        private string LogradouroField;
        
        private string NumeroField;
        
        private string PaisField;
        
        private string TipoLogradouroField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bairro
        {
            get
            {
                return this.BairroField;
            }
            set
            {
                this.BairroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CEP
        {
            get
            {
                return this.CEPField;
            }
            set
            {
                this.CEPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cidade
        {
            get
            {
                return this.CidadeField;
            }
            set
            {
                this.CidadeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Complemento
        {
            get
            {
                return this.ComplementoField;
            }
            set
            {
                this.ComplementoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Logradouro
        {
            get
            {
                return this.LogradouroField;
            }
            set
            {
                this.LogradouroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Numero
        {
            get
            {
                return this.NumeroField;
            }
            set
            {
                this.NumeroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pais
        {
            get
            {
                return this.PaisField;
            }
            set
            {
                this.PaisField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoLogradouro
        {
            get
            {
                return this.TipoLogradouroField;
            }
            set
            {
                this.TipoLogradouroField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseBase", Namespace="http://schemas.datacontract.org/2004/07/Eissnfe.Negocio.WebServices.Mensagem")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ws_osasco.CancelamentoNotaFiscalResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ws_osasco.EmissaoNotaFiscalLoteResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ws_osasco.ConsultaNotaFiscalLoteResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ws_osasco.ConsultaNotaFiscalResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ws_osasco.EmissaoNotaFiscalResponse))]
    public partial class ResponseBase : object
    {
        
        private bool ErroField;
        
        private string MensagemErroField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Erro
        {
            get
            {
                return this.ErroField;
            }
            set
            {
                this.ErroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensagemErro
        {
            get
            {
                return this.MensagemErroField;
            }
            set
            {
                this.MensagemErroField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CancelamentoNotaFiscalResponse", Namespace="http://schemas.datacontract.org/2004/07/Eissnfe.Negocio.WebServices.Mensagem")]
    public partial class CancelamentoNotaFiscalResponse : ws_osasco.ResponseBase
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmissaoNotaFiscalLoteResponse", Namespace="http://schemas.datacontract.org/2004/07/Eissnfe.Negocio.WebServices.Mensagem")]
    public partial class EmissaoNotaFiscalLoteResponse : ws_osasco.ResponseBase
    {
        
        private string MensagemField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensagem
        {
            get
            {
                return this.MensagemField;
            }
            set
            {
                this.MensagemField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsultaNotaFiscalLoteResponse", Namespace="http://schemas.datacontract.org/2004/07/Eissnfe.Negocio.WebServices.Mensagem")]
    public partial class ConsultaNotaFiscalLoteResponse : ws_osasco.ResponseBase
    {
        
        private int CodigoLoteField;
        
        private int ContadorNotasErroField;
        
        private int ContadorNotasGeradasField;
        
        private System.DateTime DataEnvioField;
        
        private System.Nullable<System.DateTime> DataFinalizacaoField;
        
        private System.Nullable<System.DateTime> DataInicioProcessamentoField;
        
        private ws_osasco.NotaFiscalLoteGeradaDTO[] NotasGeradasField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoLote
        {
            get
            {
                return this.CodigoLoteField;
            }
            set
            {
                this.CodigoLoteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ContadorNotasErro
        {
            get
            {
                return this.ContadorNotasErroField;
            }
            set
            {
                this.ContadorNotasErroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ContadorNotasGeradas
        {
            get
            {
                return this.ContadorNotasGeradasField;
            }
            set
            {
                this.ContadorNotasGeradasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataEnvio
        {
            get
            {
                return this.DataEnvioField;
            }
            set
            {
                this.DataEnvioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataFinalizacao
        {
            get
            {
                return this.DataFinalizacaoField;
            }
            set
            {
                this.DataFinalizacaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataInicioProcessamento
        {
            get
            {
                return this.DataInicioProcessamentoField;
            }
            set
            {
                this.DataInicioProcessamentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ws_osasco.NotaFiscalLoteGeradaDTO[] NotasGeradas
        {
            get
            {
                return this.NotasGeradasField;
            }
            set
            {
                this.NotasGeradasField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsultaNotaFiscalResponse", Namespace="http://schemas.datacontract.org/2004/07/Eissnfe.Negocio.WebServices.Mensagem")]
    public partial class ConsultaNotaFiscalResponse : ws_osasco.ResponseBase
    {
        
        private System.DateTime DataEnvioField;
        
        private System.DateTime DataFinalizacaoField;
        
        private ws_osasco.NotaFiscalConsultaDTO[] NotasGeradasField;
        
        private int QtdeNotasField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataEnvio
        {
            get
            {
                return this.DataEnvioField;
            }
            set
            {
                this.DataEnvioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataFinalizacao
        {
            get
            {
                return this.DataFinalizacaoField;
            }
            set
            {
                this.DataFinalizacaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ws_osasco.NotaFiscalConsultaDTO[] NotasGeradas
        {
            get
            {
                return this.NotasGeradasField;
            }
            set
            {
                this.NotasGeradasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QtdeNotas
        {
            get
            {
                return this.QtdeNotasField;
            }
            set
            {
                this.QtdeNotasField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmissaoNotaFiscalResponse", Namespace="http://schemas.datacontract.org/2004/07/Eissnfe.Negocio.WebServices.Mensagem")]
    public partial class EmissaoNotaFiscalResponse : ws_osasco.ResponseBase
    {
        
        private ws_osasco.NotaFiscalGeradaDTO NotaFiscalGeradaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ws_osasco.NotaFiscalGeradaDTO NotaFiscalGerada
        {
            get
            {
                return this.NotaFiscalGeradaField;
            }
            set
            {
                this.NotaFiscalGeradaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NotaFiscalGeradaDTO", Namespace="http://schemas.datacontract.org/2004/07/Eissnfe.Dominio.DataTransferObject.Presta" +
        "dor")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ws_osasco.NotaFiscalLoteGeradaDTO))]
    public partial class NotaFiscalGeradaDTO : object
    {
        
        private string AutenticadorField;
        
        private string LinkField;
        
        private string NumeroField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Autenticador
        {
            get
            {
                return this.AutenticadorField;
            }
            set
            {
                this.AutenticadorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Link
        {
            get
            {
                return this.LinkField;
            }
            set
            {
                this.LinkField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Numero
        {
            get
            {
                return this.NumeroField;
            }
            set
            {
                this.NumeroField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NotaFiscalLoteGeradaDTO", Namespace="http://schemas.datacontract.org/2004/07/Eissnfe.Dominio.DataTransferObject.Presta" +
        "dor")]
    public partial class NotaFiscalLoteGeradaDTO : ws_osasco.NotaFiscalGeradaDTO
    {
        
        private string EquipamentoReciboField;
        
        private bool ErroField;
        
        private string IdentificadorField;
        
        private string MensagemErroField;
        
        private string ReciboField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EquipamentoRecibo
        {
            get
            {
                return this.EquipamentoReciboField;
            }
            set
            {
                this.EquipamentoReciboField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Erro
        {
            get
            {
                return this.ErroField;
            }
            set
            {
                this.ErroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identificador
        {
            get
            {
                return this.IdentificadorField;
            }
            set
            {
                this.IdentificadorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensagemErro
        {
            get
            {
                return this.MensagemErroField;
            }
            set
            {
                this.MensagemErroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Recibo
        {
            get
            {
                return this.ReciboField;
            }
            set
            {
                this.ReciboField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NotaFiscalConsultaDTO", Namespace="http://schemas.datacontract.org/2004/07/Eissnfe.Dominio.DataTransferObject.Presta" +
        "dor")]
    public partial class NotaFiscalConsultaDTO : object
    {
        
        private System.Nullable<decimal> AliquotaField;
        
        private string CodAtividadeField;
        
        private System.Nullable<int> CodObraField;
        
        private string CodigoAutenticidadeField;
        
        private System.Nullable<System.DateTime> DataCancelamentoField;
        
        private System.DateTime DataEmissaoField;
        
        private System.Nullable<System.DateTime> DataReciboField;
        
        private string DocTomadorField;
        
        private string EnderecoPrestacaoServicoField;
        
        private string LinkNFEField;
        
        private string MotivoCancelamentoField;
        
        private string NomeTomadorField;
        
        private string NossoNumeroField;
        
        private decimal NumeroField;
        
        private System.Nullable<decimal> NumeroReciboField;
        
        private bool SubstituicaoTributariaField;
        
        private decimal ValorField;
        
        private decimal ValorIssField;
        
        private decimal ValorNFEField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Aliquota
        {
            get
            {
                return this.AliquotaField;
            }
            set
            {
                this.AliquotaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodAtividade
        {
            get
            {
                return this.CodAtividadeField;
            }
            set
            {
                this.CodAtividadeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CodObra
        {
            get
            {
                return this.CodObraField;
            }
            set
            {
                this.CodObraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoAutenticidade
        {
            get
            {
                return this.CodigoAutenticidadeField;
            }
            set
            {
                this.CodigoAutenticidadeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataCancelamento
        {
            get
            {
                return this.DataCancelamentoField;
            }
            set
            {
                this.DataCancelamentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataEmissao
        {
            get
            {
                return this.DataEmissaoField;
            }
            set
            {
                this.DataEmissaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataRecibo
        {
            get
            {
                return this.DataReciboField;
            }
            set
            {
                this.DataReciboField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocTomador
        {
            get
            {
                return this.DocTomadorField;
            }
            set
            {
                this.DocTomadorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnderecoPrestacaoServico
        {
            get
            {
                return this.EnderecoPrestacaoServicoField;
            }
            set
            {
                this.EnderecoPrestacaoServicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LinkNFE
        {
            get
            {
                return this.LinkNFEField;
            }
            set
            {
                this.LinkNFEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MotivoCancelamento
        {
            get
            {
                return this.MotivoCancelamentoField;
            }
            set
            {
                this.MotivoCancelamentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeTomador
        {
            get
            {
                return this.NomeTomadorField;
            }
            set
            {
                this.NomeTomadorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NossoNumero
        {
            get
            {
                return this.NossoNumeroField;
            }
            set
            {
                this.NossoNumeroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Numero
        {
            get
            {
                return this.NumeroField;
            }
            set
            {
                this.NumeroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> NumeroRecibo
        {
            get
            {
                return this.NumeroReciboField;
            }
            set
            {
                this.NumeroReciboField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SubstituicaoTributaria
        {
            get
            {
                return this.SubstituicaoTributariaField;
            }
            set
            {
                this.SubstituicaoTributariaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Valor
        {
            get
            {
                return this.ValorField;
            }
            set
            {
                this.ValorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ValorIss
        {
            get
            {
                return this.ValorIssField;
            }
            set
            {
                this.ValorIssField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ValorNFE
        {
            get
            {
                return this.ValorNFEField;
            }
            set
            {
                this.ValorNFEField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ws_osasco.INotaFiscalEletronicaServico")]
    public interface INotaFiscalEletronicaServico
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotaFiscalEletronicaServico/Emitir", ReplyAction="http://tempuri.org/INotaFiscalEletronicaServico/EmitirResponse")]
        ws_osasco.EmitirResponse Emitir(ws_osasco.EmitirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotaFiscalEletronicaServico/Emitir", ReplyAction="http://tempuri.org/INotaFiscalEletronicaServico/EmitirResponse")]
        System.Threading.Tasks.Task<ws_osasco.EmitirResponse> EmitirAsync(ws_osasco.EmitirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotaFiscalEletronicaServico/Cancelar", ReplyAction="http://tempuri.org/INotaFiscalEletronicaServico/CancelarResponse")]
        ws_osasco.CancelarResponse Cancelar(ws_osasco.CancelarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotaFiscalEletronicaServico/Cancelar", ReplyAction="http://tempuri.org/INotaFiscalEletronicaServico/CancelarResponse")]
        System.Threading.Tasks.Task<ws_osasco.CancelarResponse> CancelarAsync(ws_osasco.CancelarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotaFiscalEletronicaServico/EmitirEmLote", ReplyAction="http://tempuri.org/INotaFiscalEletronicaServico/EmitirEmLoteResponse")]
        ws_osasco.EmitirEmLoteResponse EmitirEmLote(ws_osasco.EmitirEmLoteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotaFiscalEletronicaServico/EmitirEmLote", ReplyAction="http://tempuri.org/INotaFiscalEletronicaServico/EmitirEmLoteResponse")]
        System.Threading.Tasks.Task<ws_osasco.EmitirEmLoteResponse> EmitirEmLoteAsync(ws_osasco.EmitirEmLoteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotaFiscalEletronicaServico/ConsultarLote", ReplyAction="http://tempuri.org/INotaFiscalEletronicaServico/ConsultarLoteResponse")]
        ws_osasco.ConsultarLoteResponse ConsultarLote(ws_osasco.ConsultarLoteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotaFiscalEletronicaServico/ConsultarLote", ReplyAction="http://tempuri.org/INotaFiscalEletronicaServico/ConsultarLoteResponse")]
        System.Threading.Tasks.Task<ws_osasco.ConsultarLoteResponse> ConsultarLoteAsync(ws_osasco.ConsultarLoteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotaFiscalEletronicaServico/Consultar", ReplyAction="http://tempuri.org/INotaFiscalEletronicaServico/ConsultarResponse")]
        ws_osasco.ConsultarResponse Consultar(ws_osasco.ConsultarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotaFiscalEletronicaServico/Consultar", ReplyAction="http://tempuri.org/INotaFiscalEletronicaServico/ConsultarResponse")]
        System.Threading.Tasks.Task<ws_osasco.ConsultarResponse> ConsultarAsync(ws_osasco.ConsultarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Emitir", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EmitirRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ws_osasco.EmissaoNotaFiscalRequest request;
        
        public EmitirRequest()
        {
        }
        
        public EmitirRequest(ws_osasco.EmissaoNotaFiscalRequest request)
        {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EmitirResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EmitirResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ws_osasco.EmissaoNotaFiscalResponse EmitirResult;
        
        public EmitirResponse()
        {
        }
        
        public EmitirResponse(ws_osasco.EmissaoNotaFiscalResponse EmitirResult)
        {
            this.EmitirResult = EmitirResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Cancelar", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CancelarRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ws_osasco.CancelamentoNotaFiscalRequest request;
        
        public CancelarRequest()
        {
        }
        
        public CancelarRequest(ws_osasco.CancelamentoNotaFiscalRequest request)
        {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelarResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CancelarResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ws_osasco.CancelamentoNotaFiscalResponse CancelarResult;
        
        public CancelarResponse()
        {
        }
        
        public CancelarResponse(ws_osasco.CancelamentoNotaFiscalResponse CancelarResult)
        {
            this.CancelarResult = CancelarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EmitirEmLote", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EmitirEmLoteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ws_osasco.EmissaoNotaFiscalLoteRequest request;
        
        public EmitirEmLoteRequest()
        {
        }
        
        public EmitirEmLoteRequest(ws_osasco.EmissaoNotaFiscalLoteRequest request)
        {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EmitirEmLoteResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EmitirEmLoteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ws_osasco.EmissaoNotaFiscalLoteResponse EmitirEmLoteResult;
        
        public EmitirEmLoteResponse()
        {
        }
        
        public EmitirEmLoteResponse(ws_osasco.EmissaoNotaFiscalLoteResponse EmitirEmLoteResult)
        {
            this.EmitirEmLoteResult = EmitirEmLoteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarLote", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConsultarLoteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ws_osasco.ConsultaNotaFiscalLoteRequest request;
        
        public ConsultarLoteRequest()
        {
        }
        
        public ConsultarLoteRequest(ws_osasco.ConsultaNotaFiscalLoteRequest request)
        {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarLoteResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConsultarLoteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ws_osasco.ConsultaNotaFiscalLoteResponse ConsultarLoteResult;
        
        public ConsultarLoteResponse()
        {
        }
        
        public ConsultarLoteResponse(ws_osasco.ConsultaNotaFiscalLoteResponse ConsultarLoteResult)
        {
            this.ConsultarLoteResult = ConsultarLoteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Consultar", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConsultarRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ws_osasco.ConsultaNotaFiscalRequest request;
        
        public ConsultarRequest()
        {
        }
        
        public ConsultarRequest(ws_osasco.ConsultaNotaFiscalRequest request)
        {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConsultarResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ws_osasco.ConsultaNotaFiscalResponse ConsultarResult;
        
        public ConsultarResponse()
        {
        }
        
        public ConsultarResponse(ws_osasco.ConsultaNotaFiscalResponse ConsultarResult)
        {
            this.ConsultarResult = ConsultarResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public interface INotaFiscalEletronicaServicoChannel : ws_osasco.INotaFiscalEletronicaServico, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public partial class NotaFiscalEletronicaServicoClient : System.ServiceModel.ClientBase<ws_osasco.INotaFiscalEletronicaServico>, ws_osasco.INotaFiscalEletronicaServico
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public NotaFiscalEletronicaServicoClient() : 
                base(NotaFiscalEletronicaServicoClient.GetDefaultBinding(), NotaFiscalEletronicaServicoClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_INotaFiscalEletronicaServico.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NotaFiscalEletronicaServicoClient(EndpointConfiguration endpointConfiguration) : 
                base(NotaFiscalEletronicaServicoClient.GetBindingForEndpoint(endpointConfiguration), NotaFiscalEletronicaServicoClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NotaFiscalEletronicaServicoClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(NotaFiscalEletronicaServicoClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NotaFiscalEletronicaServicoClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(NotaFiscalEletronicaServicoClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NotaFiscalEletronicaServicoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ws_osasco.EmitirResponse Emitir(ws_osasco.EmitirRequest request)
        {
            return base.Channel.Emitir(request);
        }
        
        public System.Threading.Tasks.Task<ws_osasco.EmitirResponse> EmitirAsync(ws_osasco.EmitirRequest request)
        {
            return base.Channel.EmitirAsync(request);
        }
        
        public ws_osasco.CancelarResponse Cancelar(ws_osasco.CancelarRequest request)
        {
            return base.Channel.Cancelar(request);
        }
        
        public System.Threading.Tasks.Task<ws_osasco.CancelarResponse> CancelarAsync(ws_osasco.CancelarRequest request)
        {
            return base.Channel.CancelarAsync(request);
        }
        
        public ws_osasco.EmitirEmLoteResponse EmitirEmLote(ws_osasco.EmitirEmLoteRequest request)
        {
            return base.Channel.EmitirEmLote(request);
        }
        
        public System.Threading.Tasks.Task<ws_osasco.EmitirEmLoteResponse> EmitirEmLoteAsync(ws_osasco.EmitirEmLoteRequest request)
        {
            return base.Channel.EmitirEmLoteAsync(request);
        }
        
        public ws_osasco.ConsultarLoteResponse ConsultarLote(ws_osasco.ConsultarLoteRequest request)
        {
            return base.Channel.ConsultarLote(request);
        }
        
        public System.Threading.Tasks.Task<ws_osasco.ConsultarLoteResponse> ConsultarLoteAsync(ws_osasco.ConsultarLoteRequest request)
        {
            return base.Channel.ConsultarLoteAsync(request);
        }
        
        public ws_osasco.ConsultarResponse Consultar(ws_osasco.ConsultarRequest request)
        {
            return base.Channel.Consultar(request);
        }
        
        public System.Threading.Tasks.Task<ws_osasco.ConsultarResponse> ConsultarAsync(ws_osasco.ConsultarRequest request)
        {
            return base.Channel.ConsultarAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_INotaFiscalEletronicaServico))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_INotaFiscalEletronicaServico))
            {
                return new System.ServiceModel.EndpointAddress("https://nfe.osasco.sp.gov.br/EissnfeWebServices/NotaFiscalEletronica.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return NotaFiscalEletronicaServicoClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_INotaFiscalEletronicaServico);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return NotaFiscalEletronicaServicoClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_INotaFiscalEletronicaServico);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_INotaFiscalEletronicaServico,
        }
    }
}
