//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ws_riodejaneiro
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://notacarioca.rio.gov.br/", ConfigurationName="ws_riodejaneiro.NfseSoap")]
    public interface NfseSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://notacarioca.rio.gov.br/ConsultarNfse", ReplyAction="*")]
        ws_riodejaneiro.ConsultarNfseResponse ConsultarNfse(ws_riodejaneiro.ConsultarNfseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://notacarioca.rio.gov.br/ConsultarNfse", ReplyAction="*")]
        System.Threading.Tasks.Task<ws_riodejaneiro.ConsultarNfseResponse> ConsultarNfseAsync(ws_riodejaneiro.ConsultarNfseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://notacarioca.rio.gov.br/ConsultarNfsePorRps", ReplyAction="*")]
        ws_riodejaneiro.ConsultarNfsePorRpsResponse ConsultarNfsePorRps(ws_riodejaneiro.ConsultarNfsePorRpsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://notacarioca.rio.gov.br/ConsultarNfsePorRps", ReplyAction="*")]
        System.Threading.Tasks.Task<ws_riodejaneiro.ConsultarNfsePorRpsResponse> ConsultarNfsePorRpsAsync(ws_riodejaneiro.ConsultarNfsePorRpsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://notacarioca.rio.gov.br/ConsultarLoteRps", ReplyAction="*")]
        ws_riodejaneiro.ConsultarLoteRpsResponse ConsultarLoteRps(ws_riodejaneiro.ConsultarLoteRpsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://notacarioca.rio.gov.br/ConsultarLoteRps", ReplyAction="*")]
        System.Threading.Tasks.Task<ws_riodejaneiro.ConsultarLoteRpsResponse> ConsultarLoteRpsAsync(ws_riodejaneiro.ConsultarLoteRpsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://notacarioca.rio.gov.br/ConsultarSituacaoLoteRps", ReplyAction="*")]
        ws_riodejaneiro.ConsultarSituacaoLoteRpsResponse ConsultarSituacaoLoteRps(ws_riodejaneiro.ConsultarSituacaoLoteRpsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://notacarioca.rio.gov.br/ConsultarSituacaoLoteRps", ReplyAction="*")]
        System.Threading.Tasks.Task<ws_riodejaneiro.ConsultarSituacaoLoteRpsResponse> ConsultarSituacaoLoteRpsAsync(ws_riodejaneiro.ConsultarSituacaoLoteRpsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://notacarioca.rio.gov.br/RecepcionarLoteRps", ReplyAction="*")]
        ws_riodejaneiro.RecepcionarLoteRpsResponse RecepcionarLoteRps(ws_riodejaneiro.RecepcionarLoteRpsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://notacarioca.rio.gov.br/RecepcionarLoteRps", ReplyAction="*")]
        System.Threading.Tasks.Task<ws_riodejaneiro.RecepcionarLoteRpsResponse> RecepcionarLoteRpsAsync(ws_riodejaneiro.RecepcionarLoteRpsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://notacarioca.rio.gov.br/CancelarNfse", ReplyAction="*")]
        ws_riodejaneiro.CancelarNfseResponse CancelarNfse(ws_riodejaneiro.CancelarNfseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://notacarioca.rio.gov.br/CancelarNfse", ReplyAction="*")]
        System.Threading.Tasks.Task<ws_riodejaneiro.CancelarNfseResponse> CancelarNfseAsync(ws_riodejaneiro.CancelarNfseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://notacarioca.rio.gov.br/GerarNfse", ReplyAction="*")]
        ws_riodejaneiro.GerarNfseResponse GerarNfse(ws_riodejaneiro.GerarNfseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://notacarioca.rio.gov.br/GerarNfse", ReplyAction="*")]
        System.Threading.Tasks.Task<ws_riodejaneiro.GerarNfseResponse> GerarNfseAsync(ws_riodejaneiro.GerarNfseRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarNfseRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarNfseRequest", Namespace="http://notacarioca.rio.gov.br/", Order=0)]
        public ws_riodejaneiro.ConsultarNfseRequestBody Body;
        
        public ConsultarNfseRequest()
        {
        }
        
        public ConsultarNfseRequest(ws_riodejaneiro.ConsultarNfseRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://notacarioca.rio.gov.br/")]
    public partial class ConsultarNfseRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string inputXML;
        
        public ConsultarNfseRequestBody()
        {
        }
        
        public ConsultarNfseRequestBody(string inputXML)
        {
            this.inputXML = inputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarNfseResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarNfseResponse", Namespace="http://notacarioca.rio.gov.br/", Order=0)]
        public ws_riodejaneiro.ConsultarNfseResponseBody Body;
        
        public ConsultarNfseResponse()
        {
        }
        
        public ConsultarNfseResponse(ws_riodejaneiro.ConsultarNfseResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://notacarioca.rio.gov.br/")]
    public partial class ConsultarNfseResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string outputXML;
        
        public ConsultarNfseResponseBody()
        {
        }
        
        public ConsultarNfseResponseBody(string outputXML)
        {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarNfsePorRpsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarNfsePorRpsRequest", Namespace="http://notacarioca.rio.gov.br/", Order=0)]
        public ws_riodejaneiro.ConsultarNfsePorRpsRequestBody Body;
        
        public ConsultarNfsePorRpsRequest()
        {
        }
        
        public ConsultarNfsePorRpsRequest(ws_riodejaneiro.ConsultarNfsePorRpsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://notacarioca.rio.gov.br/")]
    public partial class ConsultarNfsePorRpsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string inputXML;
        
        public ConsultarNfsePorRpsRequestBody()
        {
        }
        
        public ConsultarNfsePorRpsRequestBody(string inputXML)
        {
            this.inputXML = inputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarNfsePorRpsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarNfsePorRpsResponse", Namespace="http://notacarioca.rio.gov.br/", Order=0)]
        public ws_riodejaneiro.ConsultarNfsePorRpsResponseBody Body;
        
        public ConsultarNfsePorRpsResponse()
        {
        }
        
        public ConsultarNfsePorRpsResponse(ws_riodejaneiro.ConsultarNfsePorRpsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://notacarioca.rio.gov.br/")]
    public partial class ConsultarNfsePorRpsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string outputXML;
        
        public ConsultarNfsePorRpsResponseBody()
        {
        }
        
        public ConsultarNfsePorRpsResponseBody(string outputXML)
        {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarLoteRpsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarLoteRpsRequest", Namespace="http://notacarioca.rio.gov.br/", Order=0)]
        public ws_riodejaneiro.ConsultarLoteRpsRequestBody Body;
        
        public ConsultarLoteRpsRequest()
        {
        }
        
        public ConsultarLoteRpsRequest(ws_riodejaneiro.ConsultarLoteRpsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://notacarioca.rio.gov.br/")]
    public partial class ConsultarLoteRpsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string inputXML;
        
        public ConsultarLoteRpsRequestBody()
        {
        }
        
        public ConsultarLoteRpsRequestBody(string inputXML)
        {
            this.inputXML = inputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarLoteRpsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarLoteRpsResponse", Namespace="http://notacarioca.rio.gov.br/", Order=0)]
        public ws_riodejaneiro.ConsultarLoteRpsResponseBody Body;
        
        public ConsultarLoteRpsResponse()
        {
        }
        
        public ConsultarLoteRpsResponse(ws_riodejaneiro.ConsultarLoteRpsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://notacarioca.rio.gov.br/")]
    public partial class ConsultarLoteRpsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string outputXML;
        
        public ConsultarLoteRpsResponseBody()
        {
        }
        
        public ConsultarLoteRpsResponseBody(string outputXML)
        {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarSituacaoLoteRpsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarSituacaoLoteRpsRequest", Namespace="http://notacarioca.rio.gov.br/", Order=0)]
        public ws_riodejaneiro.ConsultarSituacaoLoteRpsRequestBody Body;
        
        public ConsultarSituacaoLoteRpsRequest()
        {
        }
        
        public ConsultarSituacaoLoteRpsRequest(ws_riodejaneiro.ConsultarSituacaoLoteRpsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://notacarioca.rio.gov.br/")]
    public partial class ConsultarSituacaoLoteRpsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string inputXML;
        
        public ConsultarSituacaoLoteRpsRequestBody()
        {
        }
        
        public ConsultarSituacaoLoteRpsRequestBody(string inputXML)
        {
            this.inputXML = inputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarSituacaoLoteRpsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarSituacaoLoteRpsResponse", Namespace="http://notacarioca.rio.gov.br/", Order=0)]
        public ws_riodejaneiro.ConsultarSituacaoLoteRpsResponseBody Body;
        
        public ConsultarSituacaoLoteRpsResponse()
        {
        }
        
        public ConsultarSituacaoLoteRpsResponse(ws_riodejaneiro.ConsultarSituacaoLoteRpsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://notacarioca.rio.gov.br/")]
    public partial class ConsultarSituacaoLoteRpsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string outputXML;
        
        public ConsultarSituacaoLoteRpsResponseBody()
        {
        }
        
        public ConsultarSituacaoLoteRpsResponseBody(string outputXML)
        {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecepcionarLoteRpsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RecepcionarLoteRpsRequest", Namespace="http://notacarioca.rio.gov.br/", Order=0)]
        public ws_riodejaneiro.RecepcionarLoteRpsRequestBody Body;
        
        public RecepcionarLoteRpsRequest()
        {
        }
        
        public RecepcionarLoteRpsRequest(ws_riodejaneiro.RecepcionarLoteRpsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://notacarioca.rio.gov.br/")]
    public partial class RecepcionarLoteRpsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string inputXML;
        
        public RecepcionarLoteRpsRequestBody()
        {
        }
        
        public RecepcionarLoteRpsRequestBody(string inputXML)
        {
            this.inputXML = inputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecepcionarLoteRpsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RecepcionarLoteRpsResponse", Namespace="http://notacarioca.rio.gov.br/", Order=0)]
        public ws_riodejaneiro.RecepcionarLoteRpsResponseBody Body;
        
        public RecepcionarLoteRpsResponse()
        {
        }
        
        public RecepcionarLoteRpsResponse(ws_riodejaneiro.RecepcionarLoteRpsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://notacarioca.rio.gov.br/")]
    public partial class RecepcionarLoteRpsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string outputXML;
        
        public RecepcionarLoteRpsResponseBody()
        {
        }
        
        public RecepcionarLoteRpsResponseBody(string outputXML)
        {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelarNfseRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelarNfseRequest", Namespace="http://notacarioca.rio.gov.br/", Order=0)]
        public ws_riodejaneiro.CancelarNfseRequestBody Body;
        
        public CancelarNfseRequest()
        {
        }
        
        public CancelarNfseRequest(ws_riodejaneiro.CancelarNfseRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://notacarioca.rio.gov.br/")]
    public partial class CancelarNfseRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string inputXML;
        
        public CancelarNfseRequestBody()
        {
        }
        
        public CancelarNfseRequestBody(string inputXML)
        {
            this.inputXML = inputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelarNfseResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelarNfseResponse", Namespace="http://notacarioca.rio.gov.br/", Order=0)]
        public ws_riodejaneiro.CancelarNfseResponseBody Body;
        
        public CancelarNfseResponse()
        {
        }
        
        public CancelarNfseResponse(ws_riodejaneiro.CancelarNfseResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://notacarioca.rio.gov.br/")]
    public partial class CancelarNfseResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string outputXML;
        
        public CancelarNfseResponseBody()
        {
        }
        
        public CancelarNfseResponseBody(string outputXML)
        {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GerarNfseRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GerarNfseRequest", Namespace="http://notacarioca.rio.gov.br/", Order=0)]
        public ws_riodejaneiro.GerarNfseRequestBody Body;
        
        public GerarNfseRequest()
        {
        }
        
        public GerarNfseRequest(ws_riodejaneiro.GerarNfseRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://notacarioca.rio.gov.br/")]
    public partial class GerarNfseRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string inputXML;
        
        public GerarNfseRequestBody()
        {
        }
        
        public GerarNfseRequestBody(string inputXML)
        {
            this.inputXML = inputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GerarNfseResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GerarNfseResponse", Namespace="http://notacarioca.rio.gov.br/", Order=0)]
        public ws_riodejaneiro.GerarNfseResponseBody Body;
        
        public GerarNfseResponse()
        {
        }
        
        public GerarNfseResponse(ws_riodejaneiro.GerarNfseResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://notacarioca.rio.gov.br/")]
    public partial class GerarNfseResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string outputXML;
        
        public GerarNfseResponseBody()
        {
        }
        
        public GerarNfseResponseBody(string outputXML)
        {
            this.outputXML = outputXML;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface NfseSoapChannel : ws_riodejaneiro.NfseSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class NfseSoapClient : System.ServiceModel.ClientBase<ws_riodejaneiro.NfseSoap>, ws_riodejaneiro.NfseSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public NfseSoapClient() : 
                base(NfseSoapClient.GetDefaultBinding(), NfseSoapClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.NfseSoap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NfseSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(NfseSoapClient.GetBindingForEndpoint(endpointConfiguration), NfseSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NfseSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(NfseSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NfseSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(NfseSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NfseSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ws_riodejaneiro.ConsultarNfseResponse ConsultarNfse(ws_riodejaneiro.ConsultarNfseRequest request)
        {
            return base.Channel.ConsultarNfse(request);
        }
        
        public System.Threading.Tasks.Task<ws_riodejaneiro.ConsultarNfseResponse> ConsultarNfseAsync(ws_riodejaneiro.ConsultarNfseRequest request)
        {
            return base.Channel.ConsultarNfseAsync(request);
        }
        
        public ws_riodejaneiro.ConsultarNfsePorRpsResponse ConsultarNfsePorRps(ws_riodejaneiro.ConsultarNfsePorRpsRequest request)
        {
            return base.Channel.ConsultarNfsePorRps(request);
        }
        
        public System.Threading.Tasks.Task<ws_riodejaneiro.ConsultarNfsePorRpsResponse> ConsultarNfsePorRpsAsync(ws_riodejaneiro.ConsultarNfsePorRpsRequest request)
        {
            return base.Channel.ConsultarNfsePorRpsAsync(request);
        }
        
        public ws_riodejaneiro.ConsultarLoteRpsResponse ConsultarLoteRps(ws_riodejaneiro.ConsultarLoteRpsRequest request)
        {
            return base.Channel.ConsultarLoteRps(request);
        }
        
        public System.Threading.Tasks.Task<ws_riodejaneiro.ConsultarLoteRpsResponse> ConsultarLoteRpsAsync(ws_riodejaneiro.ConsultarLoteRpsRequest request)
        {
            return base.Channel.ConsultarLoteRpsAsync(request);
        }
        
        public ws_riodejaneiro.ConsultarSituacaoLoteRpsResponse ConsultarSituacaoLoteRps(ws_riodejaneiro.ConsultarSituacaoLoteRpsRequest request)
        {
            return base.Channel.ConsultarSituacaoLoteRps(request);
        }
        
        public System.Threading.Tasks.Task<ws_riodejaneiro.ConsultarSituacaoLoteRpsResponse> ConsultarSituacaoLoteRpsAsync(ws_riodejaneiro.ConsultarSituacaoLoteRpsRequest request)
        {
            return base.Channel.ConsultarSituacaoLoteRpsAsync(request);
        }
        
        public ws_riodejaneiro.RecepcionarLoteRpsResponse RecepcionarLoteRps(ws_riodejaneiro.RecepcionarLoteRpsRequest request)
        {
            return base.Channel.RecepcionarLoteRps(request);
        }
        
        public System.Threading.Tasks.Task<ws_riodejaneiro.RecepcionarLoteRpsResponse> RecepcionarLoteRpsAsync(ws_riodejaneiro.RecepcionarLoteRpsRequest request)
        {
            return base.Channel.RecepcionarLoteRpsAsync(request);
        }
        
        public ws_riodejaneiro.CancelarNfseResponse CancelarNfse(ws_riodejaneiro.CancelarNfseRequest request)
        {
            return base.Channel.CancelarNfse(request);
        }
        
        public System.Threading.Tasks.Task<ws_riodejaneiro.CancelarNfseResponse> CancelarNfseAsync(ws_riodejaneiro.CancelarNfseRequest request)
        {
            return base.Channel.CancelarNfseAsync(request);
        }
        
        public ws_riodejaneiro.GerarNfseResponse GerarNfse(ws_riodejaneiro.GerarNfseRequest request)
        {
            return base.Channel.GerarNfse(request);
        }
        
        public System.Threading.Tasks.Task<ws_riodejaneiro.GerarNfseResponse> GerarNfseAsync(ws_riodejaneiro.GerarNfseRequest request)
        {
            return base.Channel.GerarNfseAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NfseSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NfseSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://notacarioca.rio.gov.br/WSNacional/nfse.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return NfseSoapClient.GetBindingForEndpoint(EndpointConfiguration.NfseSoap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return NfseSoapClient.GetEndpointAddress(EndpointConfiguration.NfseSoap);
        }
        
        public enum EndpointConfiguration
        {
            
            NfseSoap,
        }
    }
}
