//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ws_saopaulo
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", ConfigurationName="ws_saopaulo.LoteNFeSoap")]
    public interface LoteNFeSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/envioRPS", ReplyAction="*")]
        ws_saopaulo.EnvioRPSResponse EnvioRPS(ws_saopaulo.EnvioRPSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/envioRPS", ReplyAction="*")]
        System.Threading.Tasks.Task<ws_saopaulo.EnvioRPSResponse> EnvioRPSAsync(ws_saopaulo.EnvioRPSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/envioLoteRPS", ReplyAction="*")]
        ws_saopaulo.EnvioLoteRPSResponse EnvioLoteRPS(ws_saopaulo.EnvioLoteRPSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/envioLoteRPS", ReplyAction="*")]
        System.Threading.Tasks.Task<ws_saopaulo.EnvioLoteRPSResponse> EnvioLoteRPSAsync(ws_saopaulo.EnvioLoteRPSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/testeenvio", ReplyAction="*")]
        ws_saopaulo.TesteEnvioLoteRPSResponse TesteEnvioLoteRPS(ws_saopaulo.TesteEnvioLoteRPSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/testeenvio", ReplyAction="*")]
        System.Threading.Tasks.Task<ws_saopaulo.TesteEnvioLoteRPSResponse> TesteEnvioLoteRPSAsync(ws_saopaulo.TesteEnvioLoteRPSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/cancelamentoNFe", ReplyAction="*")]
        ws_saopaulo.CancelamentoNFeResponse CancelamentoNFe(ws_saopaulo.CancelamentoNFeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/cancelamentoNFe", ReplyAction="*")]
        System.Threading.Tasks.Task<ws_saopaulo.CancelamentoNFeResponse> CancelamentoNFeAsync(ws_saopaulo.CancelamentoNFeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaNFe", ReplyAction="*")]
        ws_saopaulo.ConsultaNFeResponse ConsultaNFe(ws_saopaulo.ConsultaNFeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaNFe", ReplyAction="*")]
        System.Threading.Tasks.Task<ws_saopaulo.ConsultaNFeResponse> ConsultaNFeAsync(ws_saopaulo.ConsultaNFeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaNFeRecebidas", ReplyAction="*")]
        ws_saopaulo.ConsultaNFeRecebidasResponse ConsultaNFeRecebidas(ws_saopaulo.ConsultaNFeRecebidasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaNFeRecebidas", ReplyAction="*")]
        System.Threading.Tasks.Task<ws_saopaulo.ConsultaNFeRecebidasResponse> ConsultaNFeRecebidasAsync(ws_saopaulo.ConsultaNFeRecebidasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaNFeEmitidas", ReplyAction="*")]
        ws_saopaulo.ConsultaNFeEmitidasResponse ConsultaNFeEmitidas(ws_saopaulo.ConsultaNFeEmitidasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaNFeEmitidas", ReplyAction="*")]
        System.Threading.Tasks.Task<ws_saopaulo.ConsultaNFeEmitidasResponse> ConsultaNFeEmitidasAsync(ws_saopaulo.ConsultaNFeEmitidasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaLote", ReplyAction="*")]
        ws_saopaulo.ConsultaLoteResponse ConsultaLote(ws_saopaulo.ConsultaLoteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaLote", ReplyAction="*")]
        System.Threading.Tasks.Task<ws_saopaulo.ConsultaLoteResponse> ConsultaLoteAsync(ws_saopaulo.ConsultaLoteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaInformacoesLote", ReplyAction="*")]
        ws_saopaulo.ConsultaInformacoesLoteResponse ConsultaInformacoesLote(ws_saopaulo.ConsultaInformacoesLoteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaInformacoesLote", ReplyAction="*")]
        System.Threading.Tasks.Task<ws_saopaulo.ConsultaInformacoesLoteResponse> ConsultaInformacoesLoteAsync(ws_saopaulo.ConsultaInformacoesLoteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaCNPJ", ReplyAction="*")]
        ws_saopaulo.ConsultaCNPJResponse ConsultaCNPJ(ws_saopaulo.ConsultaCNPJRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaCNPJ", ReplyAction="*")]
        System.Threading.Tasks.Task<ws_saopaulo.ConsultaCNPJResponse> ConsultaCNPJAsync(ws_saopaulo.ConsultaCNPJRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnvioRPSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnvioRPSRequest", Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public ws_saopaulo.EnvioRPSRequestBody Body;
        
        public EnvioRPSRequest()
        {
        }
        
        public EnvioRPSRequest(ws_saopaulo.EnvioRPSRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe")]
    public partial class EnvioRPSRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int VersaoSchema;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MensagemXML;
        
        public EnvioRPSRequestBody()
        {
        }
        
        public EnvioRPSRequestBody(int VersaoSchema, string MensagemXML)
        {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnvioRPSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnvioRPSResponse", Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public ws_saopaulo.EnvioRPSResponseBody Body;
        
        public EnvioRPSResponse()
        {
        }
        
        public EnvioRPSResponse(ws_saopaulo.EnvioRPSResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe")]
    public partial class EnvioRPSResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RetornoXML;
        
        public EnvioRPSResponseBody()
        {
        }
        
        public EnvioRPSResponseBody(string RetornoXML)
        {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnvioLoteRPSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnvioLoteRPSRequest", Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public ws_saopaulo.EnvioLoteRPSRequestBody Body;
        
        public EnvioLoteRPSRequest()
        {
        }
        
        public EnvioLoteRPSRequest(ws_saopaulo.EnvioLoteRPSRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe")]
    public partial class EnvioLoteRPSRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int VersaoSchema;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MensagemXML;
        
        public EnvioLoteRPSRequestBody()
        {
        }
        
        public EnvioLoteRPSRequestBody(int VersaoSchema, string MensagemXML)
        {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnvioLoteRPSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnvioLoteRPSResponse", Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public ws_saopaulo.EnvioLoteRPSResponseBody Body;
        
        public EnvioLoteRPSResponse()
        {
        }
        
        public EnvioLoteRPSResponse(ws_saopaulo.EnvioLoteRPSResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe")]
    public partial class EnvioLoteRPSResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RetornoXML;
        
        public EnvioLoteRPSResponseBody()
        {
        }
        
        public EnvioLoteRPSResponseBody(string RetornoXML)
        {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TesteEnvioLoteRPSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TesteEnvioLoteRPSRequest", Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public ws_saopaulo.TesteEnvioLoteRPSRequestBody Body;
        
        public TesteEnvioLoteRPSRequest()
        {
        }
        
        public TesteEnvioLoteRPSRequest(ws_saopaulo.TesteEnvioLoteRPSRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe")]
    public partial class TesteEnvioLoteRPSRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int VersaoSchema;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MensagemXML;
        
        public TesteEnvioLoteRPSRequestBody()
        {
        }
        
        public TesteEnvioLoteRPSRequestBody(int VersaoSchema, string MensagemXML)
        {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TesteEnvioLoteRPSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TesteEnvioLoteRPSResponse", Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public ws_saopaulo.TesteEnvioLoteRPSResponseBody Body;
        
        public TesteEnvioLoteRPSResponse()
        {
        }
        
        public TesteEnvioLoteRPSResponse(ws_saopaulo.TesteEnvioLoteRPSResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe")]
    public partial class TesteEnvioLoteRPSResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RetornoXML;
        
        public TesteEnvioLoteRPSResponseBody()
        {
        }
        
        public TesteEnvioLoteRPSResponseBody(string RetornoXML)
        {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelamentoNFeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelamentoNFeRequest", Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public ws_saopaulo.CancelamentoNFeRequestBody Body;
        
        public CancelamentoNFeRequest()
        {
        }
        
        public CancelamentoNFeRequest(ws_saopaulo.CancelamentoNFeRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe")]
    public partial class CancelamentoNFeRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int VersaoSchema;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MensagemXML;
        
        public CancelamentoNFeRequestBody()
        {
        }
        
        public CancelamentoNFeRequestBody(int VersaoSchema, string MensagemXML)
        {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelamentoNFeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelamentoNFeResponse", Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public ws_saopaulo.CancelamentoNFeResponseBody Body;
        
        public CancelamentoNFeResponse()
        {
        }
        
        public CancelamentoNFeResponse(ws_saopaulo.CancelamentoNFeResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe")]
    public partial class CancelamentoNFeResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RetornoXML;
        
        public CancelamentoNFeResponseBody()
        {
        }
        
        public CancelamentoNFeResponseBody(string RetornoXML)
        {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaNFeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaNFeRequest", Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public ws_saopaulo.ConsultaNFeRequestBody Body;
        
        public ConsultaNFeRequest()
        {
        }
        
        public ConsultaNFeRequest(ws_saopaulo.ConsultaNFeRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe")]
    public partial class ConsultaNFeRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int VersaoSchema;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MensagemXML;
        
        public ConsultaNFeRequestBody()
        {
        }
        
        public ConsultaNFeRequestBody(int VersaoSchema, string MensagemXML)
        {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaNFeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaNFeResponse", Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public ws_saopaulo.ConsultaNFeResponseBody Body;
        
        public ConsultaNFeResponse()
        {
        }
        
        public ConsultaNFeResponse(ws_saopaulo.ConsultaNFeResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe")]
    public partial class ConsultaNFeResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RetornoXML;
        
        public ConsultaNFeResponseBody()
        {
        }
        
        public ConsultaNFeResponseBody(string RetornoXML)
        {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaNFeRecebidasRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaNFeRecebidasRequest", Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public ws_saopaulo.ConsultaNFeRecebidasRequestBody Body;
        
        public ConsultaNFeRecebidasRequest()
        {
        }
        
        public ConsultaNFeRecebidasRequest(ws_saopaulo.ConsultaNFeRecebidasRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe")]
    public partial class ConsultaNFeRecebidasRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int VersaoSchema;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MensagemXML;
        
        public ConsultaNFeRecebidasRequestBody()
        {
        }
        
        public ConsultaNFeRecebidasRequestBody(int VersaoSchema, string MensagemXML)
        {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaNFeRecebidasResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaNFeRecebidasResponse", Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public ws_saopaulo.ConsultaNFeRecebidasResponseBody Body;
        
        public ConsultaNFeRecebidasResponse()
        {
        }
        
        public ConsultaNFeRecebidasResponse(ws_saopaulo.ConsultaNFeRecebidasResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe")]
    public partial class ConsultaNFeRecebidasResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RetornoXML;
        
        public ConsultaNFeRecebidasResponseBody()
        {
        }
        
        public ConsultaNFeRecebidasResponseBody(string RetornoXML)
        {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaNFeEmitidasRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaNFeEmitidasRequest", Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public ws_saopaulo.ConsultaNFeEmitidasRequestBody Body;
        
        public ConsultaNFeEmitidasRequest()
        {
        }
        
        public ConsultaNFeEmitidasRequest(ws_saopaulo.ConsultaNFeEmitidasRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe")]
    public partial class ConsultaNFeEmitidasRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int VersaoSchema;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MensagemXML;
        
        public ConsultaNFeEmitidasRequestBody()
        {
        }
        
        public ConsultaNFeEmitidasRequestBody(int VersaoSchema, string MensagemXML)
        {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaNFeEmitidasResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaNFeEmitidasResponse", Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public ws_saopaulo.ConsultaNFeEmitidasResponseBody Body;
        
        public ConsultaNFeEmitidasResponse()
        {
        }
        
        public ConsultaNFeEmitidasResponse(ws_saopaulo.ConsultaNFeEmitidasResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe")]
    public partial class ConsultaNFeEmitidasResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RetornoXML;
        
        public ConsultaNFeEmitidasResponseBody()
        {
        }
        
        public ConsultaNFeEmitidasResponseBody(string RetornoXML)
        {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaLoteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaLoteRequest", Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public ws_saopaulo.ConsultaLoteRequestBody Body;
        
        public ConsultaLoteRequest()
        {
        }
        
        public ConsultaLoteRequest(ws_saopaulo.ConsultaLoteRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe")]
    public partial class ConsultaLoteRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int VersaoSchema;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MensagemXML;
        
        public ConsultaLoteRequestBody()
        {
        }
        
        public ConsultaLoteRequestBody(int VersaoSchema, string MensagemXML)
        {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaLoteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaLoteResponse", Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public ws_saopaulo.ConsultaLoteResponseBody Body;
        
        public ConsultaLoteResponse()
        {
        }
        
        public ConsultaLoteResponse(ws_saopaulo.ConsultaLoteResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe")]
    public partial class ConsultaLoteResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RetornoXML;
        
        public ConsultaLoteResponseBody()
        {
        }
        
        public ConsultaLoteResponseBody(string RetornoXML)
        {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaInformacoesLoteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaInformacoesLoteRequest", Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public ws_saopaulo.ConsultaInformacoesLoteRequestBody Body;
        
        public ConsultaInformacoesLoteRequest()
        {
        }
        
        public ConsultaInformacoesLoteRequest(ws_saopaulo.ConsultaInformacoesLoteRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe")]
    public partial class ConsultaInformacoesLoteRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int VersaoSchema;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MensagemXML;
        
        public ConsultaInformacoesLoteRequestBody()
        {
        }
        
        public ConsultaInformacoesLoteRequestBody(int VersaoSchema, string MensagemXML)
        {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaInformacoesLoteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaInformacoesLoteResponse", Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public ws_saopaulo.ConsultaInformacoesLoteResponseBody Body;
        
        public ConsultaInformacoesLoteResponse()
        {
        }
        
        public ConsultaInformacoesLoteResponse(ws_saopaulo.ConsultaInformacoesLoteResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe")]
    public partial class ConsultaInformacoesLoteResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RetornoXML;
        
        public ConsultaInformacoesLoteResponseBody()
        {
        }
        
        public ConsultaInformacoesLoteResponseBody(string RetornoXML)
        {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaCNPJRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaCNPJRequest", Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public ws_saopaulo.ConsultaCNPJRequestBody Body;
        
        public ConsultaCNPJRequest()
        {
        }
        
        public ConsultaCNPJRequest(ws_saopaulo.ConsultaCNPJRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe")]
    public partial class ConsultaCNPJRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int VersaoSchema;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MensagemXML;
        
        public ConsultaCNPJRequestBody()
        {
        }
        
        public ConsultaCNPJRequestBody(int VersaoSchema, string MensagemXML)
        {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaCNPJResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaCNPJResponse", Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public ws_saopaulo.ConsultaCNPJResponseBody Body;
        
        public ConsultaCNPJResponse()
        {
        }
        
        public ConsultaCNPJResponse(ws_saopaulo.ConsultaCNPJResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe")]
    public partial class ConsultaCNPJResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RetornoXML;
        
        public ConsultaCNPJResponseBody()
        {
        }
        
        public ConsultaCNPJResponseBody(string RetornoXML)
        {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface LoteNFeSoapChannel : ws_saopaulo.LoteNFeSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class LoteNFeSoapClient : System.ServiceModel.ClientBase<ws_saopaulo.LoteNFeSoap>, ws_saopaulo.LoteNFeSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public LoteNFeSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(LoteNFeSoapClient.GetBindingForEndpoint(endpointConfiguration), LoteNFeSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LoteNFeSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(LoteNFeSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LoteNFeSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(LoteNFeSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LoteNFeSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ws_saopaulo.EnvioRPSResponse EnvioRPS(ws_saopaulo.EnvioRPSRequest request)
        {
            return base.Channel.EnvioRPS(request);
        }
        
        public System.Threading.Tasks.Task<ws_saopaulo.EnvioRPSResponse> EnvioRPSAsync(ws_saopaulo.EnvioRPSRequest request)
        {
            return base.Channel.EnvioRPSAsync(request);
        }
        
        public ws_saopaulo.EnvioLoteRPSResponse EnvioLoteRPS(ws_saopaulo.EnvioLoteRPSRequest request)
        {
            return base.Channel.EnvioLoteRPS(request);
        }
        
        public System.Threading.Tasks.Task<ws_saopaulo.EnvioLoteRPSResponse> EnvioLoteRPSAsync(ws_saopaulo.EnvioLoteRPSRequest request)
        {
            return base.Channel.EnvioLoteRPSAsync(request);
        }
        
        public ws_saopaulo.TesteEnvioLoteRPSResponse TesteEnvioLoteRPS(ws_saopaulo.TesteEnvioLoteRPSRequest request)
        {
            return base.Channel.TesteEnvioLoteRPS(request);
        }
        
        public System.Threading.Tasks.Task<ws_saopaulo.TesteEnvioLoteRPSResponse> TesteEnvioLoteRPSAsync(ws_saopaulo.TesteEnvioLoteRPSRequest request)
        {
            return base.Channel.TesteEnvioLoteRPSAsync(request);
        }
        
        public ws_saopaulo.CancelamentoNFeResponse CancelamentoNFe(ws_saopaulo.CancelamentoNFeRequest request)
        {
            return base.Channel.CancelamentoNFe(request);
        }
        
        public System.Threading.Tasks.Task<ws_saopaulo.CancelamentoNFeResponse> CancelamentoNFeAsync(ws_saopaulo.CancelamentoNFeRequest request)
        {
            return base.Channel.CancelamentoNFeAsync(request);
        }
        
        public ws_saopaulo.ConsultaNFeResponse ConsultaNFe(ws_saopaulo.ConsultaNFeRequest request)
        {
            return base.Channel.ConsultaNFe(request);
        }
        
        public System.Threading.Tasks.Task<ws_saopaulo.ConsultaNFeResponse> ConsultaNFeAsync(ws_saopaulo.ConsultaNFeRequest request)
        {
            return base.Channel.ConsultaNFeAsync(request);
        }
        
        public ws_saopaulo.ConsultaNFeRecebidasResponse ConsultaNFeRecebidas(ws_saopaulo.ConsultaNFeRecebidasRequest request)
        {
            return base.Channel.ConsultaNFeRecebidas(request);
        }
        
        public System.Threading.Tasks.Task<ws_saopaulo.ConsultaNFeRecebidasResponse> ConsultaNFeRecebidasAsync(ws_saopaulo.ConsultaNFeRecebidasRequest request)
        {
            return base.Channel.ConsultaNFeRecebidasAsync(request);
        }
        
        public ws_saopaulo.ConsultaNFeEmitidasResponse ConsultaNFeEmitidas(ws_saopaulo.ConsultaNFeEmitidasRequest request)
        {
            return base.Channel.ConsultaNFeEmitidas(request);
        }
        
        public System.Threading.Tasks.Task<ws_saopaulo.ConsultaNFeEmitidasResponse> ConsultaNFeEmitidasAsync(ws_saopaulo.ConsultaNFeEmitidasRequest request)
        {
            return base.Channel.ConsultaNFeEmitidasAsync(request);
        }
        
        public ws_saopaulo.ConsultaLoteResponse ConsultaLote(ws_saopaulo.ConsultaLoteRequest request)
        {
            return base.Channel.ConsultaLote(request);
        }
        
        public System.Threading.Tasks.Task<ws_saopaulo.ConsultaLoteResponse> ConsultaLoteAsync(ws_saopaulo.ConsultaLoteRequest request)
        {
            return base.Channel.ConsultaLoteAsync(request);
        }
        
        public ws_saopaulo.ConsultaInformacoesLoteResponse ConsultaInformacoesLote(ws_saopaulo.ConsultaInformacoesLoteRequest request)
        {
            return base.Channel.ConsultaInformacoesLote(request);
        }
        
        public System.Threading.Tasks.Task<ws_saopaulo.ConsultaInformacoesLoteResponse> ConsultaInformacoesLoteAsync(ws_saopaulo.ConsultaInformacoesLoteRequest request)
        {
            return base.Channel.ConsultaInformacoesLoteAsync(request);
        }
        
        public ws_saopaulo.ConsultaCNPJResponse ConsultaCNPJ(ws_saopaulo.ConsultaCNPJRequest request)
        {
            return base.Channel.ConsultaCNPJ(request);
        }
        
        public System.Threading.Tasks.Task<ws_saopaulo.ConsultaCNPJResponse> ConsultaCNPJAsync(ws_saopaulo.ConsultaCNPJRequest request)
        {
            return base.Channel.ConsultaCNPJAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.LoteNFeSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.LoteNFeSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.LoteNFeSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://nfe.prefeitura.sp.gov.br/ws/lotenfe.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.LoteNFeSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://nfe.prefeitura.sp.gov.br/ws/lotenfe.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            LoteNFeSoap,
            
            LoteNFeSoap12,
        }
    }
}
