//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_SaoPaulo_TaxReform
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://www.prefeitura.sp.gov.br/nfe", ConfigurationName = "WS_SaoPaulo_TaxReform.LoteNFeAsyncSoap")]
    public interface LoteNFeAsyncSoap
    {

        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (TesteEnvioLoteRPSRequest) del mensaje TesteEnvioLoteRPS no coincide con el valor predeterminado (TesteEnvioLoteRpsAsync)
        [System.ServiceModel.OperationContractAttribute(Action = "http://www.prefeitura.sp.gov.br/nfe/ws/testeEnvioLoteRPSAsync", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        WS_SaoPaulo_TaxReform.TesteEnvioLoteRPS1 TesteEnvioLoteRpsAsync(WS_SaoPaulo_TaxReform.TesteEnvioLoteRPS request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.prefeitura.sp.gov.br/nfe/ws/testeEnvioLoteRPSAsync", ReplyAction = "*")]
        System.Threading.Tasks.Task<WS_SaoPaulo_TaxReform.TesteEnvioLoteRPS1> TesteEnvioLoteRpsAsyncAsync(WS_SaoPaulo_TaxReform.TesteEnvioLoteRPS request);

        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (EnvioLoteRPSRequest) del mensaje EnvioLoteRPS no coincide con el valor predeterminado (EnvioLoteRpsAsync)
        [System.ServiceModel.OperationContractAttribute(Action = "http://www.prefeitura.sp.gov.br/nfe/ws/envioLoteRPSAsync", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        WS_SaoPaulo_TaxReform.EnvioLoteRPS1 EnvioLoteRpsAsync(WS_SaoPaulo_TaxReform.EnvioLoteRPS request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.prefeitura.sp.gov.br/nfe/ws/envioLoteRPSAsync", ReplyAction = "*")]
        System.Threading.Tasks.Task<WS_SaoPaulo_TaxReform.EnvioLoteRPS1> EnvioLoteRpsAsyncAsync(WS_SaoPaulo_TaxReform.EnvioLoteRPS request);

        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (EmissaoGuiaRequest) del mensaje EmissaoGuia no coincide con el valor predeterminado (EmissaoGuiaAsync)
        [System.ServiceModel.OperationContractAttribute(Action = "http://www.prefeitura.sp.gov.br/nfe/ws/emissaoGuia", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        WS_SaoPaulo_TaxReform.EmissaoGuia1 EmissaoGuiaAsync(WS_SaoPaulo_TaxReform.EmissaoGuia request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.prefeitura.sp.gov.br/nfe/ws/emissaoGuia", ReplyAction = "*")]
        System.Threading.Tasks.Task<WS_SaoPaulo_TaxReform.EmissaoGuia1> EmissaoGuiaAsyncAsync(WS_SaoPaulo_TaxReform.EmissaoGuia request);

        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (ConsultaSituacaoLoteRequest) del mensaje ConsultaSituacaoLote no coincide con el valor predeterminado (ConsultaSituacaoLoteSync)
        [System.ServiceModel.OperationContractAttribute(Action = "http://www.prefeitura.sp.gov.br/nfe/ws/consultaSituacaoLote", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        WS_SaoPaulo_TaxReform.ConsultaSituacaoLote1 ConsultaSituacaoLoteSync(WS_SaoPaulo_TaxReform.ConsultaSituacaoLote request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.prefeitura.sp.gov.br/nfe/ws/consultaSituacaoLote", ReplyAction = "*")]
        System.Threading.Tasks.Task<WS_SaoPaulo_TaxReform.ConsultaSituacaoLote1> ConsultaSituacaoLoteSyncAsync(WS_SaoPaulo_TaxReform.ConsultaSituacaoLote request);

        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (ConsultaSituacaoGuiaRequest) del mensaje ConsultaSituacaoGuia no coincide con el valor predeterminado (ConsultaSituacaoGuiaSync)
        [System.ServiceModel.OperationContractAttribute(Action = "http://www.prefeitura.sp.gov.br/nfe/ws/consultaSituacaoGuia", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        WS_SaoPaulo_TaxReform.ConsultaSituacaoGuia1 ConsultaSituacaoGuiaSync(WS_SaoPaulo_TaxReform.ConsultaSituacaoGuia request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.prefeitura.sp.gov.br/nfe/ws/consultaSituacaoGuia", ReplyAction = "*")]
        System.Threading.Tasks.Task<WS_SaoPaulo_TaxReform.ConsultaSituacaoGuia1> ConsultaSituacaoGuiaSyncAsync(WS_SaoPaulo_TaxReform.ConsultaSituacaoGuia request);

        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (ConsultaGuiaRequest) del mensaje ConsultaGuia no coincide con el valor predeterminado (ConsultaGuiaSync)
        [System.ServiceModel.OperationContractAttribute(Action = "http://www.prefeitura.sp.gov.br/nfe/ws/consultaGuia", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        WS_SaoPaulo_TaxReform.ConsultaGuia1 ConsultaGuiaSync(WS_SaoPaulo_TaxReform.ConsultaGuia request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.prefeitura.sp.gov.br/nfe/ws/consultaGuia", ReplyAction = "*")]
        System.Threading.Tasks.Task<WS_SaoPaulo_TaxReform.ConsultaGuia1> ConsultaGuiaSyncAsync(WS_SaoPaulo_TaxReform.ConsultaGuia request);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.prefeitura.sp.gov.br/nfe")]
    public partial class TesteEnvioLoteRPSResponseAsyncRetornoXML
    {

        private TesteEnvioLoteRPSResponseAsyncRetornoXMLCabecalho cabecalhoField;

        private tpEventoAsync[] erroField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public TesteEnvioLoteRPSResponseAsyncRetornoXMLCabecalho Cabecalho
        {
            get
            {
                return this.cabecalhoField;
            }
            set
            {
                this.cabecalhoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Erro", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public tpEventoAsync[] Erro
        {
            get
            {
                return this.erroField;
            }
            set
            {
                this.erroField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.prefeitura.sp.gov.br/nfe")]
    public partial class TesteEnvioLoteRPSResponseAsyncRetornoXMLCabecalho
    {

        private bool sucessoField;

        private tpInformacoesLoteAsync informacoesLoteField;

        private long versaoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public bool Sucesso
        {
            get
            {
                return this.sucessoField;
            }
            set
            {
                this.sucessoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public tpInformacoesLoteAsync InformacoesLote
        {
            get
            {
                return this.informacoesLoteField;
            }
            set
            {
                this.informacoesLoteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long Versao
        {
            get
            {
                return this.versaoField;
            }
            set
            {
                this.versaoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.prefeitura.sp.gov.br/nfe/tipos")]
    public partial class tpInformacoesLoteAsync
    {

        private string numeroProtocoloField;

        private System.DateTime dataRecebimentoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string NumeroProtocolo
        {
            get
            {
                return this.numeroProtocoloField;
            }
            set
            {
                this.numeroProtocoloField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public System.DateTime DataRecebimento
        {
            get
            {
                return this.dataRecebimentoField;
            }
            set
            {
                this.dataRecebimentoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.prefeitura.sp.gov.br/nfe")]
    public partial class tpStatusGuia
    {

        private string nomeField;

        private tpStatusGuiaEnum valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nome
        {
            get
            {
                return this.nomeField;
            }
            set
            {
                this.nomeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public tpStatusGuiaEnum Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.prefeitura.sp.gov.br/nfe")]
    public enum tpStatusGuiaEnum
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("7")]
        Item7,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.prefeitura.sp.gov.br/nfe")]
    public partial class tpGuia
    {

        private long inscricaoPrestadorField;

        private long numeroGuiaField;

        private bool numeroGuiaFieldSpecified;

        private string incidenciaField;

        private decimal valorTotalField;

        private bool valorTotalFieldSpecified;

        private decimal valorIssField;

        private bool valorIssFieldSpecified;

        private decimal valorTotalPagamentoField;

        private bool valorTotalPagamentoFieldSpecified;

        private tpStatusGuia statusField;

        private tpConsultaSituacaoGuias situacaoField;

        private tpEmissaoGuia referenciaField;

        private bool referenciaFieldSpecified;

        private System.DateTime dataEmissaoField;

        private bool dataEmissaoFieldSpecified;

        private System.DateTime dataVencimentoField;

        private bool dataVencimentoFieldSpecified;

        private System.DateTime dataPagamentoField;

        private bool dataPagamentoFieldSpecified;

        private System.DateTime dataQuitacaoField;

        private bool dataQuitacaoFieldSpecified;

        private System.DateTime dataCancelamentoField;

        private bool dataCancelamentoFieldSpecified;

        private string linhaDigitavelField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public long InscricaoPrestador
        {
            get
            {
                return this.inscricaoPrestadorField;
            }
            set
            {
                this.inscricaoPrestadorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public long NumeroGuia
        {
            get
            {
                return this.numeroGuiaField;
            }
            set
            {
                this.numeroGuiaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumeroGuiaSpecified
        {
            get
            {
                return this.numeroGuiaFieldSpecified;
            }
            set
            {
                this.numeroGuiaFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string Incidencia
        {
            get
            {
                return this.incidenciaField;
            }
            set
            {
                this.incidenciaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public decimal ValorTotal
        {
            get
            {
                return this.valorTotalField;
            }
            set
            {
                this.valorTotalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValorTotalSpecified
        {
            get
            {
                return this.valorTotalFieldSpecified;
            }
            set
            {
                this.valorTotalFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public decimal ValorIss
        {
            get
            {
                return this.valorIssField;
            }
            set
            {
                this.valorIssField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValorIssSpecified
        {
            get
            {
                return this.valorIssFieldSpecified;
            }
            set
            {
                this.valorIssFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public decimal ValorTotalPagamento
        {
            get
            {
                return this.valorTotalPagamentoField;
            }
            set
            {
                this.valorTotalPagamentoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValorTotalPagamentoSpecified
        {
            get
            {
                return this.valorTotalPagamentoFieldSpecified;
            }
            set
            {
                this.valorTotalPagamentoFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public tpStatusGuia Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 7)]
        public tpConsultaSituacaoGuias Situacao
        {
            get
            {
                return this.situacaoField;
            }
            set
            {
                this.situacaoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 8)]
        public tpEmissaoGuia Referencia
        {
            get
            {
                return this.referenciaField;
            }
            set
            {
                this.referenciaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReferenciaSpecified
        {
            get
            {
                return this.referenciaFieldSpecified;
            }
            set
            {
                this.referenciaFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "date", Order = 9)]
        public System.DateTime DataEmissao
        {
            get
            {
                return this.dataEmissaoField;
            }
            set
            {
                this.dataEmissaoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataEmissaoSpecified
        {
            get
            {
                return this.dataEmissaoFieldSpecified;
            }
            set
            {
                this.dataEmissaoFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "date", Order = 10)]
        public System.DateTime DataVencimento
        {
            get
            {
                return this.dataVencimentoField;
            }
            set
            {
                this.dataVencimentoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataVencimentoSpecified
        {
            get
            {
                return this.dataVencimentoFieldSpecified;
            }
            set
            {
                this.dataVencimentoFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "date", Order = 11)]
        public System.DateTime DataPagamento
        {
            get
            {
                return this.dataPagamentoField;
            }
            set
            {
                this.dataPagamentoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataPagamentoSpecified
        {
            get
            {
                return this.dataPagamentoFieldSpecified;
            }
            set
            {
                this.dataPagamentoFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "date", Order = 12)]
        public System.DateTime DataQuitacao
        {
            get
            {
                return this.dataQuitacaoField;
            }
            set
            {
                this.dataQuitacaoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataQuitacaoSpecified
        {
            get
            {
                return this.dataQuitacaoFieldSpecified;
            }
            set
            {
                this.dataQuitacaoFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "date", Order = 13)]
        public System.DateTime DataCancelamento
        {
            get
            {
                return this.dataCancelamentoField;
            }
            set
            {
                this.dataCancelamentoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataCancelamentoSpecified
        {
            get
            {
                return this.dataCancelamentoFieldSpecified;
            }
            set
            {
                this.dataCancelamentoFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 14)]
        public string LinhaDigitavel
        {
            get
            {
                return this.linhaDigitavelField;
            }
            set
            {
                this.linhaDigitavelField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.prefeitura.sp.gov.br/nfe")]
    public enum tpConsultaSituacaoGuias
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.prefeitura.sp.gov.br/nfe/tipos")]
    public enum tpEmissaoGuia
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("7")]
        Item7,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("8")]
        Item8,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.prefeitura.sp.gov.br/nfe")]
    public partial class RetornoConsultaSituacaoGuiaSituacao
    {

        private tpSituacaoGuia nomeField;

        private bool nomeFieldSpecified;

        private int valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public tpSituacaoGuia nome
        {
            get
            {
                return this.nomeField;
            }
            set
            {
                this.nomeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nomeSpecified
        {
            get
            {
                return this.nomeFieldSpecified;
            }
            set
            {
                this.nomeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public int Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.prefeitura.sp.gov.br/nfe/tipos")]
    public enum tpSituacaoGuia
    {

        /// <remarks/>
        solicitada,

        /// <remarks/>
        invalidada,

        /// <remarks/>
        verificada,

        /// <remarks/>
        processada,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.prefeitura.sp.gov.br/nfe")]
    public partial class RetornoConsultaSituacaoLoteSituacao
    {

        private tpSituacaoLote nomeField;

        private bool nomeFieldSpecified;

        private int valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public tpSituacaoLote nome
        {
            get
            {
                return this.nomeField;
            }
            set
            {
                this.nomeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nomeSpecified
        {
            get
            {
                return this.nomeFieldSpecified;
            }
            set
            {
                this.nomeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public int Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.prefeitura.sp.gov.br/nfe/tipos")]
    public enum tpSituacaoLote
    {

        /// <remarks/>
        enviado,

        /// <remarks/>
        invalidado,

        /// <remarks/>
        verificado,

        /// <remarks/>
        processado,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.prefeitura.sp.gov.br/nfe/tipos")]
    public partial class tpInformacoesGuiaAsync
    {

        private string numeroProtocoloField;

        private System.DateTime dataRecebimentoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string NumeroProtocolo
        {
            get
            {
                return this.numeroProtocoloField;
            }
            set
            {
                this.numeroProtocoloField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public System.DateTime DataRecebimento
        {
            get
            {
                return this.dataRecebimentoField;
            }
            set
            {
                this.dataRecebimentoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.prefeitura.sp.gov.br/nfe/tipos")]
    public partial class tpEventoAsync
    {

        private short codigoField;

        private string descricaoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public short Codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string Descricao
        {
            get
            {
                return this.descricaoField;
            }
            set
            {
                this.descricaoField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "TesteEnvioLoteRPSRequest", WrapperNamespace = "http://www.prefeitura.sp.gov.br/nfe", IsWrapped = true)]
    public partial class TesteEnvioLoteRPS
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.prefeitura.sp.gov.br/nfe", Order = 0)]
        public int versaoSchema;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.prefeitura.sp.gov.br/nfe", Order = 1)]
        public string MensagemXML;

        public TesteEnvioLoteRPS()
        {
        }

        public TesteEnvioLoteRPS(int versaoSchema, string MensagemXML)
        {
            this.versaoSchema = versaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "TesteEnvioLoteRPSResponseAsync", WrapperNamespace = "http://www.prefeitura.sp.gov.br/nfe", IsWrapped = true)]
    public partial class TesteEnvioLoteRPS1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.prefeitura.sp.gov.br/nfe", Order = 0)]
        public WS_SaoPaulo_TaxReform.TesteEnvioLoteRPSResponseAsyncRetornoXML RetornoXML;

        public TesteEnvioLoteRPS1()
        {
        }

        public TesteEnvioLoteRPS1(WS_SaoPaulo_TaxReform.TesteEnvioLoteRPSResponseAsyncRetornoXML RetornoXML)
        {
            this.RetornoXML = RetornoXML;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.prefeitura.sp.gov.br/nfe")]
    public partial class EnvioLoteRPSResponseAsyncRetornoXML
    {

        private EnvioLoteRPSResponseAsyncRetornoXMLCabecalho cabecalhoField;

        private tpEventoAsync[] erroField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public EnvioLoteRPSResponseAsyncRetornoXMLCabecalho Cabecalho
        {
            get
            {
                return this.cabecalhoField;
            }
            set
            {
                this.cabecalhoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Erro", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public tpEventoAsync[] Erro
        {
            get
            {
                return this.erroField;
            }
            set
            {
                this.erroField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.prefeitura.sp.gov.br/nfe")]
    public partial class EnvioLoteRPSResponseAsyncRetornoXMLCabecalho
    {

        private bool sucessoField;

        private tpInformacoesLoteAsync informacoesLoteField;

        private long versaoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public bool Sucesso
        {
            get
            {
                return this.sucessoField;
            }
            set
            {
                this.sucessoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public tpInformacoesLoteAsync InformacoesLote
        {
            get
            {
                return this.informacoesLoteField;
            }
            set
            {
                this.informacoesLoteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long Versao
        {
            get
            {
                return this.versaoField;
            }
            set
            {
                this.versaoField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "EnvioLoteRPSRequest", WrapperNamespace = "http://www.prefeitura.sp.gov.br/nfe", IsWrapped = true)]
    public partial class EnvioLoteRPS
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.prefeitura.sp.gov.br/nfe", Order = 0)]
        public int versaoSchema;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.prefeitura.sp.gov.br/nfe", Order = 1)]
        public string MensagemXML;

        public EnvioLoteRPS()
        {
        }

        public EnvioLoteRPS(int versaoSchema, string MensagemXML)
        {
            this.versaoSchema = versaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "EnvioLoteRPSResponseAsync", WrapperNamespace = "http://www.prefeitura.sp.gov.br/nfe", IsWrapped = true)]
    public partial class EnvioLoteRPS1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.prefeitura.sp.gov.br/nfe", Order = 0)]
        public WS_SaoPaulo_TaxReform.EnvioLoteRPSResponseAsyncRetornoXML RetornoXML;

        public EnvioLoteRPS1()
        {
        }

        public EnvioLoteRPS1(WS_SaoPaulo_TaxReform.EnvioLoteRPSResponseAsyncRetornoXML RetornoXML)
        {
            this.RetornoXML = RetornoXML;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.prefeitura.sp.gov.br/nfe")]
    public partial class EmissaoGuiaResponseRetornoEmissaoGuiaAsync
    {

        private EmissaoGuiaResponseRetornoEmissaoGuiaAsyncCabecalho cabecalhoField;

        private tpEventoAsync[] erroField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public EmissaoGuiaResponseRetornoEmissaoGuiaAsyncCabecalho Cabecalho
        {
            get
            {
                return this.cabecalhoField;
            }
            set
            {
                this.cabecalhoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Erro", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public tpEventoAsync[] Erro
        {
            get
            {
                return this.erroField;
            }
            set
            {
                this.erroField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.prefeitura.sp.gov.br/nfe")]
    public partial class EmissaoGuiaResponseRetornoEmissaoGuiaAsyncCabecalho
    {

        private bool sucessoField;

        private tpInformacoesGuiaAsync informacoesGuiaField;

        private long versaoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public bool Sucesso
        {
            get
            {
                return this.sucessoField;
            }
            set
            {
                this.sucessoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public tpInformacoesGuiaAsync InformacoesGuia
        {
            get
            {
                return this.informacoesGuiaField;
            }
            set
            {
                this.informacoesGuiaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long Versao
        {
            get
            {
                return this.versaoField;
            }
            set
            {
                this.versaoField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "EmissaoGuiaRequest", WrapperNamespace = "http://www.prefeitura.sp.gov.br/nfe", IsWrapped = true)]
    public partial class EmissaoGuia
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.prefeitura.sp.gov.br/nfe", Order = 0)]
        public int versaoSchema;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.prefeitura.sp.gov.br/nfe", Order = 1)]
        public string MensagemXML;

        public EmissaoGuia()
        {
        }

        public EmissaoGuia(int versaoSchema, string MensagemXML)
        {
            this.versaoSchema = versaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "EmissaoGuiaResponse", WrapperNamespace = "http://www.prefeitura.sp.gov.br/nfe", IsWrapped = true)]
    public partial class EmissaoGuia1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.prefeitura.sp.gov.br/nfe", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public WS_SaoPaulo_TaxReform.EmissaoGuiaResponseRetornoEmissaoGuiaAsync RetornoEmissaoGuiaAsync;

        public EmissaoGuia1()
        {
        }

        public EmissaoGuia1(WS_SaoPaulo_TaxReform.EmissaoGuiaResponseRetornoEmissaoGuiaAsync RetornoEmissaoGuiaAsync)
        {
            this.RetornoEmissaoGuiaAsync = RetornoEmissaoGuiaAsync;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.prefeitura.sp.gov.br/nfe")]
    public partial class ConsultaSituacaoLoteResponseRetornoXML
    {

        private bool sucessoField;

        private RetornoConsultaSituacaoLoteSituacao situacaoField;

        private long numeroLoteField;

        private bool numeroLoteFieldSpecified;

        private System.DateTime dataRecebimentoField;

        private bool dataRecebimentoFieldSpecified;

        private System.DateTime dataProcessamentoField;

        private bool dataProcessamentoFieldSpecified;

        private string resultadoOperacaoField;

        private tpEventoAsync[] erroField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public bool Sucesso
        {
            get
            {
                return this.sucessoField;
            }
            set
            {
                this.sucessoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public RetornoConsultaSituacaoLoteSituacao Situacao
        {
            get
            {
                return this.situacaoField;
            }
            set
            {
                this.situacaoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public long NumeroLote
        {
            get
            {
                return this.numeroLoteField;
            }
            set
            {
                this.numeroLoteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumeroLoteSpecified
        {
            get
            {
                return this.numeroLoteFieldSpecified;
            }
            set
            {
                this.numeroLoteFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public System.DateTime DataRecebimento
        {
            get
            {
                return this.dataRecebimentoField;
            }
            set
            {
                this.dataRecebimentoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataRecebimentoSpecified
        {
            get
            {
                return this.dataRecebimentoFieldSpecified;
            }
            set
            {
                this.dataRecebimentoFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public System.DateTime DataProcessamento
        {
            get
            {
                return this.dataProcessamentoField;
            }
            set
            {
                this.dataProcessamentoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataProcessamentoSpecified
        {
            get
            {
                return this.dataProcessamentoFieldSpecified;
            }
            set
            {
                this.dataProcessamentoFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public string ResultadoOperacao
        {
            get
            {
                return this.resultadoOperacaoField;
            }
            set
            {
                this.resultadoOperacaoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Erro", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public tpEventoAsync[] Erro
        {
            get
            {
                return this.erroField;
            }
            set
            {
                this.erroField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "ConsultaSituacaoLoteRequest", WrapperNamespace = "http://www.prefeitura.sp.gov.br/nfe", IsWrapped = true)]
    public partial class ConsultaSituacaoLote
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.prefeitura.sp.gov.br/nfe", Order = 0)]
        public int versaoSchema;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.prefeitura.sp.gov.br/nfe", Order = 1)]
        public string MensagemXML;

        public ConsultaSituacaoLote()
        {
        }

        public ConsultaSituacaoLote(int versaoSchema, string MensagemXML)
        {
            this.versaoSchema = versaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "ConsultaSituacaoLoteResponse", WrapperNamespace = "http://www.prefeitura.sp.gov.br/nfe", IsWrapped = true)]
    public partial class ConsultaSituacaoLote1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.prefeitura.sp.gov.br/nfe", Order = 0)]
        public WS_SaoPaulo_TaxReform.ConsultaSituacaoLoteResponseRetornoXML RetornoXML;

        public ConsultaSituacaoLote1()
        {
        }

        public ConsultaSituacaoLote1(WS_SaoPaulo_TaxReform.ConsultaSituacaoLoteResponseRetornoXML RetornoXML)
        {
            this.RetornoXML = RetornoXML;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.prefeitura.sp.gov.br/nfe")]
    public partial class ConsultaSituacaoGuiaResponseRetornoXML
    {

        private bool sucessoField;

        private RetornoConsultaSituacaoGuiaSituacao situacaoField;

        private long numeroGuiaField;

        private bool numeroGuiaFieldSpecified;

        private System.DateTime dataRecebimentoField;

        private bool dataRecebimentoFieldSpecified;

        private System.DateTime dataProcessamentoField;

        private bool dataProcessamentoFieldSpecified;

        private string resultadoOperacaoField;

        private tpEventoAsync[] erroField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public bool Sucesso
        {
            get
            {
                return this.sucessoField;
            }
            set
            {
                this.sucessoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public RetornoConsultaSituacaoGuiaSituacao Situacao
        {
            get
            {
                return this.situacaoField;
            }
            set
            {
                this.situacaoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public long NumeroGuia
        {
            get
            {
                return this.numeroGuiaField;
            }
            set
            {
                this.numeroGuiaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumeroGuiaSpecified
        {
            get
            {
                return this.numeroGuiaFieldSpecified;
            }
            set
            {
                this.numeroGuiaFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public System.DateTime DataRecebimento
        {
            get
            {
                return this.dataRecebimentoField;
            }
            set
            {
                this.dataRecebimentoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataRecebimentoSpecified
        {
            get
            {
                return this.dataRecebimentoFieldSpecified;
            }
            set
            {
                this.dataRecebimentoFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public System.DateTime DataProcessamento
        {
            get
            {
                return this.dataProcessamentoField;
            }
            set
            {
                this.dataProcessamentoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataProcessamentoSpecified
        {
            get
            {
                return this.dataProcessamentoFieldSpecified;
            }
            set
            {
                this.dataProcessamentoFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public string ResultadoOperacao
        {
            get
            {
                return this.resultadoOperacaoField;
            }
            set
            {
                this.resultadoOperacaoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Erro", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public tpEventoAsync[] Erro
        {
            get
            {
                return this.erroField;
            }
            set
            {
                this.erroField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "ConsultaSituacaoGuiaRequest", WrapperNamespace = "http://www.prefeitura.sp.gov.br/nfe", IsWrapped = true)]
    public partial class ConsultaSituacaoGuia
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.prefeitura.sp.gov.br/nfe", Order = 0)]
        public int versaoSchema;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.prefeitura.sp.gov.br/nfe", Order = 1)]
        public string MensagemXML;

        public ConsultaSituacaoGuia()
        {
        }

        public ConsultaSituacaoGuia(int versaoSchema, string MensagemXML)
        {
            this.versaoSchema = versaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "ConsultaSituacaoGuiaResponse", WrapperNamespace = "http://www.prefeitura.sp.gov.br/nfe", IsWrapped = true)]
    public partial class ConsultaSituacaoGuia1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.prefeitura.sp.gov.br/nfe", Order = 0)]
        public WS_SaoPaulo_TaxReform.ConsultaSituacaoGuiaResponseRetornoXML RetornoXML;

        public ConsultaSituacaoGuia1()
        {
        }

        public ConsultaSituacaoGuia1(WS_SaoPaulo_TaxReform.ConsultaSituacaoGuiaResponseRetornoXML RetornoXML)
        {
            this.RetornoXML = RetornoXML;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.prefeitura.sp.gov.br/nfe")]
    public partial class ConsultaGuiaResponseRetornoConsultaGuia
    {

        private ConsultaGuiaResponseRetornoConsultaGuiaCabecalho cabecalhoField;

        private tpGuia[] guiaField;

        private tpEventoAsync[] erroField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public ConsultaGuiaResponseRetornoConsultaGuiaCabecalho Cabecalho
        {
            get
            {
                return this.cabecalhoField;
            }
            set
            {
                this.cabecalhoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Guia", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public tpGuia[] Guia
        {
            get
            {
                return this.guiaField;
            }
            set
            {
                this.guiaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Erro", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public tpEventoAsync[] Erro
        {
            get
            {
                return this.erroField;
            }
            set
            {
                this.erroField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.prefeitura.sp.gov.br/nfe")]
    public partial class ConsultaGuiaResponseRetornoConsultaGuiaCabecalho
    {

        private bool sucessoField;

        private long versaoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public bool Sucesso
        {
            get
            {
                return this.sucessoField;
            }
            set
            {
                this.sucessoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long Versao
        {
            get
            {
                return this.versaoField;
            }
            set
            {
                this.versaoField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "ConsultaGuiaRequest", WrapperNamespace = "http://www.prefeitura.sp.gov.br/nfe", IsWrapped = true)]
    public partial class ConsultaGuia
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.prefeitura.sp.gov.br/nfe", Order = 0)]
        public int versaoSchema;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.prefeitura.sp.gov.br/nfe", Order = 1)]
        public string MensagemXML;

        public ConsultaGuia()
        {
        }

        public ConsultaGuia(int versaoSchema, string MensagemXML)
        {
            this.versaoSchema = versaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "ConsultaGuiaResponse", WrapperNamespace = "http://www.prefeitura.sp.gov.br/nfe", IsWrapped = true)]
    public partial class ConsultaGuia1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.prefeitura.sp.gov.br/nfe", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public WS_SaoPaulo_TaxReform.ConsultaGuiaResponseRetornoConsultaGuia RetornoConsultaGuia;

        public ConsultaGuia1()
        {
        }

        public ConsultaGuia1(WS_SaoPaulo_TaxReform.ConsultaGuiaResponseRetornoConsultaGuia RetornoConsultaGuia)
        {
            this.RetornoConsultaGuia = RetornoConsultaGuia;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface LoteNFeAsyncSoapChannel : WS_SaoPaulo_TaxReform.LoteNFeAsyncSoap, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class LoteNFeAsyncSoapClient : System.ServiceModel.ClientBase<WS_SaoPaulo_TaxReform.LoteNFeAsyncSoap>, WS_SaoPaulo_TaxReform.LoteNFeAsyncSoap
    {

        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

        public LoteNFeAsyncSoapClient(EndpointConfiguration endpointConfiguration) :
                base(LoteNFeAsyncSoapClient.GetBindingForEndpoint(endpointConfiguration), LoteNFeAsyncSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public LoteNFeAsyncSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) :
                base(LoteNFeAsyncSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public LoteNFeAsyncSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) :
                base(LoteNFeAsyncSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public LoteNFeAsyncSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS_SaoPaulo_TaxReform.TesteEnvioLoteRPS1 WS_SaoPaulo_TaxReform.LoteNFeAsyncSoap.TesteEnvioLoteRpsAsync(WS_SaoPaulo_TaxReform.TesteEnvioLoteRPS request)
        {
            return base.Channel.TesteEnvioLoteRpsAsync(request);
        }

        public WS_SaoPaulo_TaxReform.TesteEnvioLoteRPSResponseAsyncRetornoXML TesteEnvioLoteRpsAsync(int versaoSchema, string MensagemXML)
        {
            WS_SaoPaulo_TaxReform.TesteEnvioLoteRPS inValue = new WS_SaoPaulo_TaxReform.TesteEnvioLoteRPS();
            inValue.versaoSchema = versaoSchema;
            inValue.MensagemXML = MensagemXML;
            WS_SaoPaulo_TaxReform.TesteEnvioLoteRPS1 retVal = ((WS_SaoPaulo_TaxReform.LoteNFeAsyncSoap)(this)).TesteEnvioLoteRpsAsync(inValue);
            return retVal.RetornoXML;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS_SaoPaulo_TaxReform.TesteEnvioLoteRPS1> WS_SaoPaulo_TaxReform.LoteNFeAsyncSoap.TesteEnvioLoteRpsAsyncAsync(WS_SaoPaulo_TaxReform.TesteEnvioLoteRPS request)
        {
            return base.Channel.TesteEnvioLoteRpsAsyncAsync(request);
        }

        public System.Threading.Tasks.Task<WS_SaoPaulo_TaxReform.TesteEnvioLoteRPS1> TesteEnvioLoteRpsAsyncAsync(int versaoSchema, string MensagemXML)
        {
            WS_SaoPaulo_TaxReform.TesteEnvioLoteRPS inValue = new WS_SaoPaulo_TaxReform.TesteEnvioLoteRPS();
            inValue.versaoSchema = versaoSchema;
            inValue.MensagemXML = MensagemXML;
            return ((WS_SaoPaulo_TaxReform.LoteNFeAsyncSoap)(this)).TesteEnvioLoteRpsAsyncAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS_SaoPaulo_TaxReform.EnvioLoteRPS1 WS_SaoPaulo_TaxReform.LoteNFeAsyncSoap.EnvioLoteRpsAsync(WS_SaoPaulo_TaxReform.EnvioLoteRPS request)
        {
            return base.Channel.EnvioLoteRpsAsync(request);
        }

        public WS_SaoPaulo_TaxReform.EnvioLoteRPSResponseAsyncRetornoXML EnvioLoteRpsAsync(int versaoSchema, string MensagemXML)
        {
            WS_SaoPaulo_TaxReform.EnvioLoteRPS inValue = new WS_SaoPaulo_TaxReform.EnvioLoteRPS();
            inValue.versaoSchema = versaoSchema;
            inValue.MensagemXML = MensagemXML;
            WS_SaoPaulo_TaxReform.EnvioLoteRPS1 retVal = ((WS_SaoPaulo_TaxReform.LoteNFeAsyncSoap)(this)).EnvioLoteRpsAsync(inValue);
            return retVal.RetornoXML;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS_SaoPaulo_TaxReform.EnvioLoteRPS1> WS_SaoPaulo_TaxReform.LoteNFeAsyncSoap.EnvioLoteRpsAsyncAsync(WS_SaoPaulo_TaxReform.EnvioLoteRPS request)
        {
            return base.Channel.EnvioLoteRpsAsyncAsync(request);
        }

        public System.Threading.Tasks.Task<WS_SaoPaulo_TaxReform.EnvioLoteRPS1> EnvioLoteRpsAsyncAsync(int versaoSchema, string MensagemXML)
        {
            WS_SaoPaulo_TaxReform.EnvioLoteRPS inValue = new WS_SaoPaulo_TaxReform.EnvioLoteRPS();
            inValue.versaoSchema = versaoSchema;
            inValue.MensagemXML = MensagemXML;
            return ((WS_SaoPaulo_TaxReform.LoteNFeAsyncSoap)(this)).EnvioLoteRpsAsyncAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS_SaoPaulo_TaxReform.EmissaoGuia1 WS_SaoPaulo_TaxReform.LoteNFeAsyncSoap.EmissaoGuiaAsync(WS_SaoPaulo_TaxReform.EmissaoGuia request)
        {
            return base.Channel.EmissaoGuiaAsync(request);
        }

        public WS_SaoPaulo_TaxReform.EmissaoGuiaResponseRetornoEmissaoGuiaAsync EmissaoGuiaAsync(int versaoSchema, string MensagemXML)
        {
            WS_SaoPaulo_TaxReform.EmissaoGuia inValue = new WS_SaoPaulo_TaxReform.EmissaoGuia();
            inValue.versaoSchema = versaoSchema;
            inValue.MensagemXML = MensagemXML;
            WS_SaoPaulo_TaxReform.EmissaoGuia1 retVal = ((WS_SaoPaulo_TaxReform.LoteNFeAsyncSoap)(this)).EmissaoGuiaAsync(inValue);
            return retVal.RetornoEmissaoGuiaAsync;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS_SaoPaulo_TaxReform.EmissaoGuia1> WS_SaoPaulo_TaxReform.LoteNFeAsyncSoap.EmissaoGuiaAsyncAsync(WS_SaoPaulo_TaxReform.EmissaoGuia request)
        {
            return base.Channel.EmissaoGuiaAsyncAsync(request);
        }

        public System.Threading.Tasks.Task<WS_SaoPaulo_TaxReform.EmissaoGuia1> EmissaoGuiaAsyncAsync(int versaoSchema, string MensagemXML)
        {
            WS_SaoPaulo_TaxReform.EmissaoGuia inValue = new WS_SaoPaulo_TaxReform.EmissaoGuia();
            inValue.versaoSchema = versaoSchema;
            inValue.MensagemXML = MensagemXML;
            return ((WS_SaoPaulo_TaxReform.LoteNFeAsyncSoap)(this)).EmissaoGuiaAsyncAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS_SaoPaulo_TaxReform.ConsultaSituacaoLote1 WS_SaoPaulo_TaxReform.LoteNFeAsyncSoap.ConsultaSituacaoLoteSync(WS_SaoPaulo_TaxReform.ConsultaSituacaoLote request)
        {
            return base.Channel.ConsultaSituacaoLoteSync(request);
        }

        public WS_SaoPaulo_TaxReform.ConsultaSituacaoLoteResponseRetornoXML ConsultaSituacaoLoteSync(int versaoSchema, string MensagemXML)
        {
            WS_SaoPaulo_TaxReform.ConsultaSituacaoLote inValue = new WS_SaoPaulo_TaxReform.ConsultaSituacaoLote();
            inValue.versaoSchema = versaoSchema;
            inValue.MensagemXML = MensagemXML;
            WS_SaoPaulo_TaxReform.ConsultaSituacaoLote1 retVal = ((WS_SaoPaulo_TaxReform.LoteNFeAsyncSoap)(this)).ConsultaSituacaoLoteSync(inValue);
            return retVal.RetornoXML;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS_SaoPaulo_TaxReform.ConsultaSituacaoLote1> WS_SaoPaulo_TaxReform.LoteNFeAsyncSoap.ConsultaSituacaoLoteSyncAsync(WS_SaoPaulo_TaxReform.ConsultaSituacaoLote request)
        {
            return base.Channel.ConsultaSituacaoLoteSyncAsync(request);
        }

        public System.Threading.Tasks.Task<WS_SaoPaulo_TaxReform.ConsultaSituacaoLote1> ConsultaSituacaoLoteSyncAsync(int versaoSchema, string MensagemXML)
        {
            WS_SaoPaulo_TaxReform.ConsultaSituacaoLote inValue = new WS_SaoPaulo_TaxReform.ConsultaSituacaoLote();
            inValue.versaoSchema = versaoSchema;
            inValue.MensagemXML = MensagemXML;
            return ((WS_SaoPaulo_TaxReform.LoteNFeAsyncSoap)(this)).ConsultaSituacaoLoteSyncAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS_SaoPaulo_TaxReform.ConsultaSituacaoGuia1 WS_SaoPaulo_TaxReform.LoteNFeAsyncSoap.ConsultaSituacaoGuiaSync(WS_SaoPaulo_TaxReform.ConsultaSituacaoGuia request)
        {
            return base.Channel.ConsultaSituacaoGuiaSync(request);
        }

        public WS_SaoPaulo_TaxReform.ConsultaSituacaoGuiaResponseRetornoXML ConsultaSituacaoGuiaSync(int versaoSchema, string MensagemXML)
        {
            WS_SaoPaulo_TaxReform.ConsultaSituacaoGuia inValue = new WS_SaoPaulo_TaxReform.ConsultaSituacaoGuia();
            inValue.versaoSchema = versaoSchema;
            inValue.MensagemXML = MensagemXML;
            WS_SaoPaulo_TaxReform.ConsultaSituacaoGuia1 retVal = ((WS_SaoPaulo_TaxReform.LoteNFeAsyncSoap)(this)).ConsultaSituacaoGuiaSync(inValue);
            return retVal.RetornoXML;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS_SaoPaulo_TaxReform.ConsultaSituacaoGuia1> WS_SaoPaulo_TaxReform.LoteNFeAsyncSoap.ConsultaSituacaoGuiaSyncAsync(WS_SaoPaulo_TaxReform.ConsultaSituacaoGuia request)
        {
            return base.Channel.ConsultaSituacaoGuiaSyncAsync(request);
        }

        public System.Threading.Tasks.Task<WS_SaoPaulo_TaxReform.ConsultaSituacaoGuia1> ConsultaSituacaoGuiaSyncAsync(int versaoSchema, string MensagemXML)
        {
            WS_SaoPaulo_TaxReform.ConsultaSituacaoGuia inValue = new WS_SaoPaulo_TaxReform.ConsultaSituacaoGuia();
            inValue.versaoSchema = versaoSchema;
            inValue.MensagemXML = MensagemXML;
            return ((WS_SaoPaulo_TaxReform.LoteNFeAsyncSoap)(this)).ConsultaSituacaoGuiaSyncAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS_SaoPaulo_TaxReform.ConsultaGuia1 WS_SaoPaulo_TaxReform.LoteNFeAsyncSoap.ConsultaGuiaSync(WS_SaoPaulo_TaxReform.ConsultaGuia request)
        {
            return base.Channel.ConsultaGuiaSync(request);
        }

        public WS_SaoPaulo_TaxReform.ConsultaGuiaResponseRetornoConsultaGuia ConsultaGuiaSync(int versaoSchema, string MensagemXML)
        {
            WS_SaoPaulo_TaxReform.ConsultaGuia inValue = new WS_SaoPaulo_TaxReform.ConsultaGuia();
            inValue.versaoSchema = versaoSchema;
            inValue.MensagemXML = MensagemXML;
            WS_SaoPaulo_TaxReform.ConsultaGuia1 retVal = ((WS_SaoPaulo_TaxReform.LoteNFeAsyncSoap)(this)).ConsultaGuiaSync(inValue);
            return retVal.RetornoConsultaGuia;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS_SaoPaulo_TaxReform.ConsultaGuia1> WS_SaoPaulo_TaxReform.LoteNFeAsyncSoap.ConsultaGuiaSyncAsync(WS_SaoPaulo_TaxReform.ConsultaGuia request)
        {
            return base.Channel.ConsultaGuiaSyncAsync(request);
        }

        public System.Threading.Tasks.Task<WS_SaoPaulo_TaxReform.ConsultaGuia1> ConsultaGuiaSyncAsync(int versaoSchema, string MensagemXML)
        {
            WS_SaoPaulo_TaxReform.ConsultaGuia inValue = new WS_SaoPaulo_TaxReform.ConsultaGuia();
            inValue.versaoSchema = versaoSchema;
            inValue.MensagemXML = MensagemXML;
            return ((WS_SaoPaulo_TaxReform.LoteNFeAsyncSoap)(this)).ConsultaGuiaSyncAsync(inValue);
        }

        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }

        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }

        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.LoteNFeAsyncSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.LoteNFeAsyncSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }

        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.LoteNFeAsyncSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://nfews.prefeitura.sp.gov.br/lotenfeasync.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.LoteNFeAsyncSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://nfews.prefeitura.sp.gov.br/lotenfeasync.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }

        public enum EndpointConfiguration
        {

            LoteNFeAsyncSoap,

            LoteNFeAsyncSoap12,
        }
    }
}
