//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsSaoCaetano
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://nfse.abrasf.org.br", ConfigurationName = "wsSaoCaetano.nfse")]
    public interface nfse
    {

        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (ConsultarNfsePorRpsRequest) del mensaje ConsultarNfsePorRps no coincide con el valor predeterminado (ConsultarNfsePorRps)
        [System.ServiceModel.OperationContractAttribute(Action = "http://nfse.abrasf.org.br/ConsultarNfsePorRps", ReplyAction = "*")]
        wsSaoCaetano.ConsultarNfsePorRpsResponse ConsultarNfsePorRps(wsSaoCaetano.ConsultarNfsePorRps request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://nfse.abrasf.org.br/ConsultarNfsePorRps", ReplyAction = "*")]
        System.Threading.Tasks.Task<wsSaoCaetano.ConsultarNfsePorRpsResponse> ConsultarNfsePorRpsAsync(wsSaoCaetano.ConsultarNfsePorRps request);

        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (ConsultarNfseServicoTomadoRequest) del mensaje ConsultarNfseServicoTomado no coincide con el valor predeterminado (ConsultarNfseServicoTomado)
        [System.ServiceModel.OperationContractAttribute(Action = "http://nfse.abrasf.org.br/ConsultarNfseServicoTomado", ReplyAction = "*")]
        wsSaoCaetano.ConsultarNfseServicoTomadoResponse ConsultarNfseServicoTomado(wsSaoCaetano.ConsultarNfseServicoTomado request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://nfse.abrasf.org.br/ConsultarNfseServicoTomado", ReplyAction = "*")]
        System.Threading.Tasks.Task<wsSaoCaetano.ConsultarNfseServicoTomadoResponse> ConsultarNfseServicoTomadoAsync(wsSaoCaetano.ConsultarNfseServicoTomado request);

        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (RecepcionarLoteRpsRequest) del mensaje RecepcionarLoteRps no coincide con el valor predeterminado (RecepcionarLoteRps)
        [System.ServiceModel.OperationContractAttribute(Action = "http://nfse.abrasf.org.br/RecepcionarLoteRps", ReplyAction = "*")]
        wsSaoCaetano.RecepcionarLoteRpsResponse RecepcionarLoteRps(wsSaoCaetano.RecepcionarLoteRps request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://nfse.abrasf.org.br/RecepcionarLoteRps", ReplyAction = "*")]
        System.Threading.Tasks.Task<wsSaoCaetano.RecepcionarLoteRpsResponse> RecepcionarLoteRpsAsync(wsSaoCaetano.RecepcionarLoteRps request);

        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (RecepcionarLoteRpsSincronoRequest) del mensaje RecepcionarLoteRpsSincrono no coincide con el valor predeterminado (RecepcionarLoteRpsSincrono)
        [System.ServiceModel.OperationContractAttribute(Action = "http://nfse.abrasf.org.br/RecepcionarLoteRpsSincrono", ReplyAction = "*")]
        wsSaoCaetano.RecepcionarLoteRpsSincronoResponse RecepcionarLoteRpsSincrono(wsSaoCaetano.RecepcionarLoteRpsSincrono request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://nfse.abrasf.org.br/RecepcionarLoteRpsSincrono", ReplyAction = "*")]
        System.Threading.Tasks.Task<wsSaoCaetano.RecepcionarLoteRpsSincronoResponse> RecepcionarLoteRpsSincronoAsync(wsSaoCaetano.RecepcionarLoteRpsSincrono request);

        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (ConsultarNfseServicoPrestadoRequest) del mensaje ConsultarNfseServicoPrestado no coincide con el valor predeterminado (ConsultarNfseServicoPrestado)
        [System.ServiceModel.OperationContractAttribute(Action = "http://nfse.abrasf.org.br/ConsultarNfseServicoPrestado", ReplyAction = "*")]
        wsSaoCaetano.ConsultarNfseServicoPrestadoResponse ConsultarNfseServicoPrestado(wsSaoCaetano.ConsultarNfseServicoPrestado request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://nfse.abrasf.org.br/ConsultarNfseServicoPrestado", ReplyAction = "*")]
        System.Threading.Tasks.Task<wsSaoCaetano.ConsultarNfseServicoPrestadoResponse> ConsultarNfseServicoPrestadoAsync(wsSaoCaetano.ConsultarNfseServicoPrestado request);

        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (CancelarNfseRequest) del mensaje CancelarNfse no coincide con el valor predeterminado (CancelarNfse)
        [System.ServiceModel.OperationContractAttribute(Action = "http://nfse.abrasf.org.br/CancelarNfse", ReplyAction = "*")]
        wsSaoCaetano.CancelarNfseResponse CancelarNfse(wsSaoCaetano.CancelarNfse request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://nfse.abrasf.org.br/CancelarNfse", ReplyAction = "*")]
        System.Threading.Tasks.Task<wsSaoCaetano.CancelarNfseResponse> CancelarNfseAsync(wsSaoCaetano.CancelarNfse request);

        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (ConsultarLoteRpsRequest) del mensaje ConsultarLoteRps no coincide con el valor predeterminado (ConsultarLoteRps)
        [System.ServiceModel.OperationContractAttribute(Action = "http://nfse.abrasf.org.br/ConsultarLoteRps", ReplyAction = "*")]
        wsSaoCaetano.ConsultarLoteRpsResponse ConsultarLoteRps(wsSaoCaetano.ConsultarLoteRps request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://nfse.abrasf.org.br/ConsultarLoteRps", ReplyAction = "*")]
        System.Threading.Tasks.Task<wsSaoCaetano.ConsultarLoteRpsResponse> ConsultarLoteRpsAsync(wsSaoCaetano.ConsultarLoteRps request);

        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (GerarNfseRequest) del mensaje GerarNfse no coincide con el valor predeterminado (GerarNfse)
        [System.ServiceModel.OperationContractAttribute(Action = "http://nfse.abrasf.org.br/GerarNfse", ReplyAction = "*")]
        wsSaoCaetano.GerarNfseResponse GerarNfse(wsSaoCaetano.GerarNfse request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://nfse.abrasf.org.br/GerarNfse", ReplyAction = "*")]
        System.Threading.Tasks.Task<wsSaoCaetano.GerarNfseResponse> GerarNfseAsync(wsSaoCaetano.GerarNfse request);

        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (SubstituirNfseRequest) del mensaje SubstituirNfse no coincide con el valor predeterminado (SubstituirNfse)
        [System.ServiceModel.OperationContractAttribute(Action = "http://nfse.abrasf.org.br/SubstituirNfse", ReplyAction = "*")]
        wsSaoCaetano.SubstituirNfseResponse SubstituirNfse(wsSaoCaetano.SubstituirNfse request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://nfse.abrasf.org.br/SubstituirNfse", ReplyAction = "*")]
        System.Threading.Tasks.Task<wsSaoCaetano.SubstituirNfseResponse> SubstituirNfseAsync(wsSaoCaetano.SubstituirNfse request);

        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (ConsultarNfsePorFaixaRequest) del mensaje ConsultarNfsePorFaixa no coincide con el valor predeterminado (ConsultarNfsePorFaixa)
        [System.ServiceModel.OperationContractAttribute(Action = "http://nfse.abrasf.org.br/ConsultarNfsePorFaixa", ReplyAction = "*")]
        wsSaoCaetano.ConsultarNfsePorFaixaResponse ConsultarNfsePorFaixa(wsSaoCaetano.ConsultarNfsePorFaixa request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://nfse.abrasf.org.br/ConsultarNfsePorFaixa", ReplyAction = "*")]
        System.Threading.Tasks.Task<wsSaoCaetano.ConsultarNfsePorFaixaResponse> ConsultarNfsePorFaixaAsync(wsSaoCaetano.ConsultarNfsePorFaixa request);
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "ConsultarNfsePorRpsRequest", WrapperNamespace = "http://nfse.abrasf.org.br", IsWrapped = true)]
    public partial class ConsultarNfsePorRps
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public string nfseCabecMsg;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 1)]
        public string nfseDadosMsg;

        public ConsultarNfsePorRps()
        {
        }

        public ConsultarNfsePorRps(string nfseCabecMsg, string nfseDadosMsg)
        {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "ConsultarNfsePorRpsResponse", WrapperNamespace = "http://nfse.abrasf.org.br", IsWrapped = true)]
    public partial class ConsultarNfsePorRpsResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public string outputXML;

        public ConsultarNfsePorRpsResponse()
        {
        }

        public ConsultarNfsePorRpsResponse(string outputXML)
        {
            this.outputXML = outputXML;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "ConsultarNfseServicoTomadoRequest", WrapperNamespace = "http://nfse.abrasf.org.br", IsWrapped = true)]
    public partial class ConsultarNfseServicoTomado
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public string nfseCabecMsg;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 1)]
        public string nfseDadosMsg;

        public ConsultarNfseServicoTomado()
        {
        }

        public ConsultarNfseServicoTomado(string nfseCabecMsg, string nfseDadosMsg)
        {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "ConsultarNfseServicoTomadoResponse", WrapperNamespace = "http://nfse.abrasf.org.br", IsWrapped = true)]
    public partial class ConsultarNfseServicoTomadoResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public string outputXML;

        public ConsultarNfseServicoTomadoResponse()
        {
        }

        public ConsultarNfseServicoTomadoResponse(string outputXML)
        {
            this.outputXML = outputXML;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "RecepcionarLoteRpsRequest", WrapperNamespace = "http://nfse.abrasf.org.br", IsWrapped = true)]
    public partial class RecepcionarLoteRps
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public string nfseCabecMsg;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 1)]
        public string nfseDadosMsg;

        public RecepcionarLoteRps()
        {
        }

        public RecepcionarLoteRps(string nfseCabecMsg, string nfseDadosMsg)
        {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "RecepcionarLoteRpsResponse", WrapperNamespace = "http://nfse.abrasf.org.br", IsWrapped = true)]
    public partial class RecepcionarLoteRpsResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public string outputXML;

        public RecepcionarLoteRpsResponse()
        {
        }

        public RecepcionarLoteRpsResponse(string outputXML)
        {
            this.outputXML = outputXML;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "RecepcionarLoteRpsSincronoRequest", WrapperNamespace = "http://nfse.abrasf.org.br", IsWrapped = true)]
    public partial class RecepcionarLoteRpsSincrono
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public string nfseCabecMsg;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 1)]
        public string nfseDadosMsg;

        public RecepcionarLoteRpsSincrono()
        {
        }

        public RecepcionarLoteRpsSincrono(string nfseCabecMsg, string nfseDadosMsg)
        {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "RecepcionarLoteRpsSincronoResponse", WrapperNamespace = "http://nfse.abrasf.org.br", IsWrapped = true)]
    public partial class RecepcionarLoteRpsSincronoResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public string outputXML;

        public RecepcionarLoteRpsSincronoResponse()
        {
        }

        public RecepcionarLoteRpsSincronoResponse(string outputXML)
        {
            this.outputXML = outputXML;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "ConsultarNfseServicoPrestadoRequest", WrapperNamespace = "http://nfse.abrasf.org.br", IsWrapped = true)]
    public partial class ConsultarNfseServicoPrestado
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public string nfseCabecMsg;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 1)]
        public string nfseDadosMsg;

        public ConsultarNfseServicoPrestado()
        {
        }

        public ConsultarNfseServicoPrestado(string nfseCabecMsg, string nfseDadosMsg)
        {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "ConsultarNfseServicoPrestadoResponse", WrapperNamespace = "http://nfse.abrasf.org.br", IsWrapped = true)]
    public partial class ConsultarNfseServicoPrestadoResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public string outputXML;

        public ConsultarNfseServicoPrestadoResponse()
        {
        }

        public ConsultarNfseServicoPrestadoResponse(string outputXML)
        {
            this.outputXML = outputXML;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "CancelarNfseRequest", WrapperNamespace = "http://nfse.abrasf.org.br", IsWrapped = true)]
    public partial class CancelarNfse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public string nfseCabecMsg;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 1)]
        public string nfseDadosMsg;

        public CancelarNfse()
        {
        }

        public CancelarNfse(string nfseCabecMsg, string nfseDadosMsg)
        {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "CancelarNfseResponse", WrapperNamespace = "http://nfse.abrasf.org.br", IsWrapped = true)]
    public partial class CancelarNfseResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public string outputXML;

        public CancelarNfseResponse()
        {
        }

        public CancelarNfseResponse(string outputXML)
        {
            this.outputXML = outputXML;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "ConsultarLoteRpsRequest", WrapperNamespace = "http://nfse.abrasf.org.br", IsWrapped = true)]
    public partial class ConsultarLoteRps
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public string nfseCabecMsg;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 1)]
        public string nfseDadosMsg;

        public ConsultarLoteRps()
        {
        }

        public ConsultarLoteRps(string nfseCabecMsg, string nfseDadosMsg)
        {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "ConsultarLoteRpsResponse", WrapperNamespace = "http://nfse.abrasf.org.br", IsWrapped = true)]
    public partial class ConsultarLoteRpsResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public string outputXML;

        public ConsultarLoteRpsResponse()
        {
        }

        public ConsultarLoteRpsResponse(string outputXML)
        {
            this.outputXML = outputXML;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GerarNfseRequest", WrapperNamespace = "http://nfse.abrasf.org.br", IsWrapped = true)]
    public partial class GerarNfse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public string nfseCabecMsg;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 1)]
        public string nfseDadosMsg;

        public GerarNfse()
        {
        }

        public GerarNfse(string nfseCabecMsg, string nfseDadosMsg)
        {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GerarNfseResponse", WrapperNamespace = "http://nfse.abrasf.org.br", IsWrapped = true)]
    public partial class GerarNfseResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public string outputXML;

        public GerarNfseResponse()
        {
        }

        public GerarNfseResponse(string outputXML)
        {
            this.outputXML = outputXML;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "SubstituirNfseRequest", WrapperNamespace = "http://nfse.abrasf.org.br", IsWrapped = true)]
    public partial class SubstituirNfse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public string nfseCabecMsg;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 1)]
        public string nfseDadosMsg;

        public SubstituirNfse()
        {
        }

        public SubstituirNfse(string nfseCabecMsg, string nfseDadosMsg)
        {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "SubstituirNfseResponse", WrapperNamespace = "http://nfse.abrasf.org.br", IsWrapped = true)]
    public partial class SubstituirNfseResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public string outputXML;

        public SubstituirNfseResponse()
        {
        }

        public SubstituirNfseResponse(string outputXML)
        {
            this.outputXML = outputXML;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "ConsultarNfsePorFaixaRequest", WrapperNamespace = "http://nfse.abrasf.org.br", IsWrapped = true)]
    public partial class ConsultarNfsePorFaixa
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public string nfseCabecMsg;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 1)]
        public string nfseDadosMsg;

        public ConsultarNfsePorFaixa()
        {
        }

        public ConsultarNfsePorFaixa(string nfseCabecMsg, string nfseDadosMsg)
        {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "ConsultarNfsePorFaixaResponse", WrapperNamespace = "http://nfse.abrasf.org.br", IsWrapped = true)]
    public partial class ConsultarNfsePorFaixaResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public string outputXML;

        public ConsultarNfsePorFaixaResponse()
        {
        }

        public ConsultarNfsePorFaixaResponse(string outputXML)
        {
            this.outputXML = outputXML;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface nfseChannel : wsSaoCaetano.nfse, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class nfseClient : System.ServiceModel.ClientBase<wsSaoCaetano.nfse>, wsSaoCaetano.nfse
    {

        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

        public nfseClient() :
                base(nfseClient.GetDefaultBinding(), nfseClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.NfseImplPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public nfseClient(EndpointConfiguration endpointConfiguration) :
                base(nfseClient.GetBindingForEndpoint(endpointConfiguration), nfseClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public nfseClient(EndpointConfiguration endpointConfiguration, string remoteAddress) :
                base(nfseClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public nfseClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) :
                base(nfseClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public nfseClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsSaoCaetano.ConsultarNfsePorRpsResponse wsSaoCaetano.nfse.ConsultarNfsePorRps(wsSaoCaetano.ConsultarNfsePorRps request)
        {
            return base.Channel.ConsultarNfsePorRps(request);
        }

        public string ConsultarNfsePorRps(string nfseCabecMsg, string nfseDadosMsg)
        {
            wsSaoCaetano.ConsultarNfsePorRps inValue = new wsSaoCaetano.ConsultarNfsePorRps();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            wsSaoCaetano.ConsultarNfsePorRpsResponse retVal = ((wsSaoCaetano.nfse)(this)).ConsultarNfsePorRps(inValue);
            return retVal.outputXML;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsSaoCaetano.ConsultarNfsePorRpsResponse> wsSaoCaetano.nfse.ConsultarNfsePorRpsAsync(wsSaoCaetano.ConsultarNfsePorRps request)
        {
            return base.Channel.ConsultarNfsePorRpsAsync(request);
        }

        public System.Threading.Tasks.Task<wsSaoCaetano.ConsultarNfsePorRpsResponse> ConsultarNfsePorRpsAsync(string nfseCabecMsg, string nfseDadosMsg)
        {
            wsSaoCaetano.ConsultarNfsePorRps inValue = new wsSaoCaetano.ConsultarNfsePorRps();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            return ((wsSaoCaetano.nfse)(this)).ConsultarNfsePorRpsAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsSaoCaetano.ConsultarNfseServicoTomadoResponse wsSaoCaetano.nfse.ConsultarNfseServicoTomado(wsSaoCaetano.ConsultarNfseServicoTomado request)
        {
            return base.Channel.ConsultarNfseServicoTomado(request);
        }

        public string ConsultarNfseServicoTomado(string nfseCabecMsg, string nfseDadosMsg)
        {
            wsSaoCaetano.ConsultarNfseServicoTomado inValue = new wsSaoCaetano.ConsultarNfseServicoTomado();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            wsSaoCaetano.ConsultarNfseServicoTomadoResponse retVal = ((wsSaoCaetano.nfse)(this)).ConsultarNfseServicoTomado(inValue);
            return retVal.outputXML;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsSaoCaetano.ConsultarNfseServicoTomadoResponse> wsSaoCaetano.nfse.ConsultarNfseServicoTomadoAsync(wsSaoCaetano.ConsultarNfseServicoTomado request)
        {
            return base.Channel.ConsultarNfseServicoTomadoAsync(request);
        }

        public System.Threading.Tasks.Task<wsSaoCaetano.ConsultarNfseServicoTomadoResponse> ConsultarNfseServicoTomadoAsync(string nfseCabecMsg, string nfseDadosMsg)
        {
            wsSaoCaetano.ConsultarNfseServicoTomado inValue = new wsSaoCaetano.ConsultarNfseServicoTomado();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            return ((wsSaoCaetano.nfse)(this)).ConsultarNfseServicoTomadoAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsSaoCaetano.RecepcionarLoteRpsResponse wsSaoCaetano.nfse.RecepcionarLoteRps(wsSaoCaetano.RecepcionarLoteRps request)
        {
            return base.Channel.RecepcionarLoteRps(request);
        }

        public string RecepcionarLoteRps(string nfseCabecMsg, string nfseDadosMsg)
        {
            wsSaoCaetano.RecepcionarLoteRps inValue = new wsSaoCaetano.RecepcionarLoteRps();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            wsSaoCaetano.RecepcionarLoteRpsResponse retVal = ((wsSaoCaetano.nfse)(this)).RecepcionarLoteRps(inValue);
            return retVal.outputXML;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsSaoCaetano.RecepcionarLoteRpsResponse> wsSaoCaetano.nfse.RecepcionarLoteRpsAsync(wsSaoCaetano.RecepcionarLoteRps request)
        {
            return base.Channel.RecepcionarLoteRpsAsync(request);
        }

        public System.Threading.Tasks.Task<wsSaoCaetano.RecepcionarLoteRpsResponse> RecepcionarLoteRpsAsync(string nfseCabecMsg, string nfseDadosMsg)
        {
            wsSaoCaetano.RecepcionarLoteRps inValue = new wsSaoCaetano.RecepcionarLoteRps();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            return ((wsSaoCaetano.nfse)(this)).RecepcionarLoteRpsAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsSaoCaetano.RecepcionarLoteRpsSincronoResponse wsSaoCaetano.nfse.RecepcionarLoteRpsSincrono(wsSaoCaetano.RecepcionarLoteRpsSincrono request)
        {
            return base.Channel.RecepcionarLoteRpsSincrono(request);
        }

        public string RecepcionarLoteRpsSincrono(string nfseCabecMsg, string nfseDadosMsg)
        {
            wsSaoCaetano.RecepcionarLoteRpsSincrono inValue = new wsSaoCaetano.RecepcionarLoteRpsSincrono();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            wsSaoCaetano.RecepcionarLoteRpsSincronoResponse retVal = ((wsSaoCaetano.nfse)(this)).RecepcionarLoteRpsSincrono(inValue);
            return retVal.outputXML;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsSaoCaetano.RecepcionarLoteRpsSincronoResponse> wsSaoCaetano.nfse.RecepcionarLoteRpsSincronoAsync(wsSaoCaetano.RecepcionarLoteRpsSincrono request)
        {
            return base.Channel.RecepcionarLoteRpsSincronoAsync(request);
        }

        public System.Threading.Tasks.Task<wsSaoCaetano.RecepcionarLoteRpsSincronoResponse> RecepcionarLoteRpsSincronoAsync(string nfseCabecMsg, string nfseDadosMsg)
        {
            wsSaoCaetano.RecepcionarLoteRpsSincrono inValue = new wsSaoCaetano.RecepcionarLoteRpsSincrono();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            return ((wsSaoCaetano.nfse)(this)).RecepcionarLoteRpsSincronoAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsSaoCaetano.ConsultarNfseServicoPrestadoResponse wsSaoCaetano.nfse.ConsultarNfseServicoPrestado(wsSaoCaetano.ConsultarNfseServicoPrestado request)
        {
            return base.Channel.ConsultarNfseServicoPrestado(request);
        }

        public string ConsultarNfseServicoPrestado(string nfseCabecMsg, string nfseDadosMsg)
        {
            wsSaoCaetano.ConsultarNfseServicoPrestado inValue = new wsSaoCaetano.ConsultarNfseServicoPrestado();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            wsSaoCaetano.ConsultarNfseServicoPrestadoResponse retVal = ((wsSaoCaetano.nfse)(this)).ConsultarNfseServicoPrestado(inValue);
            return retVal.outputXML;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsSaoCaetano.ConsultarNfseServicoPrestadoResponse> wsSaoCaetano.nfse.ConsultarNfseServicoPrestadoAsync(wsSaoCaetano.ConsultarNfseServicoPrestado request)
        {
            return base.Channel.ConsultarNfseServicoPrestadoAsync(request);
        }

        public System.Threading.Tasks.Task<wsSaoCaetano.ConsultarNfseServicoPrestadoResponse> ConsultarNfseServicoPrestadoAsync(string nfseCabecMsg, string nfseDadosMsg)
        {
            wsSaoCaetano.ConsultarNfseServicoPrestado inValue = new wsSaoCaetano.ConsultarNfseServicoPrestado();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            return ((wsSaoCaetano.nfse)(this)).ConsultarNfseServicoPrestadoAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsSaoCaetano.CancelarNfseResponse wsSaoCaetano.nfse.CancelarNfse(wsSaoCaetano.CancelarNfse request)
        {
            return base.Channel.CancelarNfse(request);
        }

        public string CancelarNfse(string nfseCabecMsg, string nfseDadosMsg)
        {
            wsSaoCaetano.CancelarNfse inValue = new wsSaoCaetano.CancelarNfse();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            wsSaoCaetano.CancelarNfseResponse retVal = ((wsSaoCaetano.nfse)(this)).CancelarNfse(inValue);
            return retVal.outputXML;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsSaoCaetano.CancelarNfseResponse> wsSaoCaetano.nfse.CancelarNfseAsync(wsSaoCaetano.CancelarNfse request)
        {
            return base.Channel.CancelarNfseAsync(request);
        }

        public System.Threading.Tasks.Task<wsSaoCaetano.CancelarNfseResponse> CancelarNfseAsync(string nfseCabecMsg, string nfseDadosMsg)
        {
            wsSaoCaetano.CancelarNfse inValue = new wsSaoCaetano.CancelarNfse();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            return ((wsSaoCaetano.nfse)(this)).CancelarNfseAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsSaoCaetano.ConsultarLoteRpsResponse wsSaoCaetano.nfse.ConsultarLoteRps(wsSaoCaetano.ConsultarLoteRps request)
        {
            return base.Channel.ConsultarLoteRps(request);
        }

        public string ConsultarLoteRps(string nfseCabecMsg, string nfseDadosMsg)
        {
            wsSaoCaetano.ConsultarLoteRps inValue = new wsSaoCaetano.ConsultarLoteRps();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            wsSaoCaetano.ConsultarLoteRpsResponse retVal = ((wsSaoCaetano.nfse)(this)).ConsultarLoteRps(inValue);
            return retVal.outputXML;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsSaoCaetano.ConsultarLoteRpsResponse> wsSaoCaetano.nfse.ConsultarLoteRpsAsync(wsSaoCaetano.ConsultarLoteRps request)
        {
            return base.Channel.ConsultarLoteRpsAsync(request);
        }

        public System.Threading.Tasks.Task<wsSaoCaetano.ConsultarLoteRpsResponse> ConsultarLoteRpsAsync(string nfseCabecMsg, string nfseDadosMsg)
        {
            wsSaoCaetano.ConsultarLoteRps inValue = new wsSaoCaetano.ConsultarLoteRps();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            return ((wsSaoCaetano.nfse)(this)).ConsultarLoteRpsAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsSaoCaetano.GerarNfseResponse wsSaoCaetano.nfse.GerarNfse(wsSaoCaetano.GerarNfse request)
        {
            return base.Channel.GerarNfse(request);
        }

        public string GerarNfse(string nfseCabecMsg, string nfseDadosMsg)
        {
            wsSaoCaetano.GerarNfse inValue = new wsSaoCaetano.GerarNfse();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            wsSaoCaetano.GerarNfseResponse retVal = ((wsSaoCaetano.nfse)(this)).GerarNfse(inValue);
            return retVal.outputXML;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsSaoCaetano.GerarNfseResponse> wsSaoCaetano.nfse.GerarNfseAsync(wsSaoCaetano.GerarNfse request)
        {
            return base.Channel.GerarNfseAsync(request);
        }

        public System.Threading.Tasks.Task<wsSaoCaetano.GerarNfseResponse> GerarNfseAsync(string nfseCabecMsg, string nfseDadosMsg)
        {
            wsSaoCaetano.GerarNfse inValue = new wsSaoCaetano.GerarNfse();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            return ((wsSaoCaetano.nfse)(this)).GerarNfseAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsSaoCaetano.SubstituirNfseResponse wsSaoCaetano.nfse.SubstituirNfse(wsSaoCaetano.SubstituirNfse request)
        {
            return base.Channel.SubstituirNfse(request);
        }

        public string SubstituirNfse(string nfseCabecMsg, string nfseDadosMsg)
        {
            wsSaoCaetano.SubstituirNfse inValue = new wsSaoCaetano.SubstituirNfse();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            wsSaoCaetano.SubstituirNfseResponse retVal = ((wsSaoCaetano.nfse)(this)).SubstituirNfse(inValue);
            return retVal.outputXML;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsSaoCaetano.SubstituirNfseResponse> wsSaoCaetano.nfse.SubstituirNfseAsync(wsSaoCaetano.SubstituirNfse request)
        {
            return base.Channel.SubstituirNfseAsync(request);
        }

        public System.Threading.Tasks.Task<wsSaoCaetano.SubstituirNfseResponse> SubstituirNfseAsync(string nfseCabecMsg, string nfseDadosMsg)
        {
            wsSaoCaetano.SubstituirNfse inValue = new wsSaoCaetano.SubstituirNfse();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            return ((wsSaoCaetano.nfse)(this)).SubstituirNfseAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsSaoCaetano.ConsultarNfsePorFaixaResponse wsSaoCaetano.nfse.ConsultarNfsePorFaixa(wsSaoCaetano.ConsultarNfsePorFaixa request)
        {
            return base.Channel.ConsultarNfsePorFaixa(request);
        }

        public string ConsultarNfsePorFaixa(string nfseCabecMsg, string nfseDadosMsg)
        {
            wsSaoCaetano.ConsultarNfsePorFaixa inValue = new wsSaoCaetano.ConsultarNfsePorFaixa();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            wsSaoCaetano.ConsultarNfsePorFaixaResponse retVal = ((wsSaoCaetano.nfse)(this)).ConsultarNfsePorFaixa(inValue);
            return retVal.outputXML;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsSaoCaetano.ConsultarNfsePorFaixaResponse> wsSaoCaetano.nfse.ConsultarNfsePorFaixaAsync(wsSaoCaetano.ConsultarNfsePorFaixa request)
        {
            return base.Channel.ConsultarNfsePorFaixaAsync(request);
        }

        public System.Threading.Tasks.Task<wsSaoCaetano.ConsultarNfsePorFaixaResponse> ConsultarNfsePorFaixaAsync(string nfseCabecMsg, string nfseDadosMsg)
        {
            wsSaoCaetano.ConsultarNfsePorFaixa inValue = new wsSaoCaetano.ConsultarNfsePorFaixa();
            inValue.nfseCabecMsg = nfseCabecMsg;
            inValue.nfseDadosMsg = nfseDadosMsg;
            return ((wsSaoCaetano.nfse)(this)).ConsultarNfsePorFaixaAsync(inValue);
        }

        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }

        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }

        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NfseImplPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }

        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NfseImplPort))
            {
                return new System.ServiceModel.EndpointAddress("https://ws-scs.giss.com.br/service-ws/nf/nfse-ws");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }

        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return nfseClient.GetBindingForEndpoint(EndpointConfiguration.NfseImplPort);
        }

        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return nfseClient.GetEndpointAddress(EndpointConfiguration.NfseImplPort);
        }

        public enum EndpointConfiguration
        {

            NfseImplPort,
        }
    }
}
