//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ws_fortaleza
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://producao.issfortaleza.com.br", ConfigurationName="ws_fortaleza.ServiceGinfes")]
    public interface ServiceGinfes
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ws_fortaleza.CancelarNfseResponse CancelarNfse(ws_fortaleza.CancelarNfse request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ws_fortaleza.CancelarNfseResponse> CancelarNfseAsync(ws_fortaleza.CancelarNfse request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ws_fortaleza.RecepcionarLoteRpsV3Response RecepcionarLoteRpsV3(ws_fortaleza.RecepcionarLoteRpsV3 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ws_fortaleza.RecepcionarLoteRpsV3Response> RecepcionarLoteRpsV3Async(ws_fortaleza.RecepcionarLoteRpsV3 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ws_fortaleza.ConsultarLoteRpsV3Response ConsultarLoteRpsV3(ws_fortaleza.ConsultarLoteRpsV3 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ws_fortaleza.ConsultarLoteRpsV3Response> ConsultarLoteRpsV3Async(ws_fortaleza.ConsultarLoteRpsV3 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ws_fortaleza.ConsultarNfsePorRpsV3Response ConsultarNfsePorRpsV3(ws_fortaleza.ConsultarNfsePorRpsV3 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ws_fortaleza.ConsultarNfsePorRpsV3Response> ConsultarNfsePorRpsV3Async(ws_fortaleza.ConsultarNfsePorRpsV3 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ws_fortaleza.ConsultarNfseV3Response ConsultarNfseV3(ws_fortaleza.ConsultarNfseV3 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ws_fortaleza.ConsultarNfseV3Response> ConsultarNfseV3Async(ws_fortaleza.ConsultarNfseV3 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ws_fortaleza.ConsultarSituacaoLoteRpsV3Response ConsultarSituacaoLoteRpsV3(ws_fortaleza.ConsultarSituacaoLoteRpsV3 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ws_fortaleza.ConsultarSituacaoLoteRpsV3Response> ConsultarSituacaoLoteRpsV3Async(ws_fortaleza.ConsultarSituacaoLoteRpsV3 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelarNfse", WrapperNamespace="http://producao.issfortaleza.com.br", IsWrapped=true)]
    public partial class CancelarNfse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string CancelarNfseEnvio;
        
        public CancelarNfse()
        {
        }
        
        public CancelarNfse(string CancelarNfseEnvio)
        {
            this.CancelarNfseEnvio = CancelarNfseEnvio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelarNfseResponse", WrapperNamespace="http://producao.issfortaleza.com.br", IsWrapped=true)]
    public partial class CancelarNfseResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string CancelarNfseResposta;
        
        public CancelarNfseResponse()
        {
        }
        
        public CancelarNfseResponse(string CancelarNfseResposta)
        {
            this.CancelarNfseResposta = CancelarNfseResposta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RecepcionarLoteRpsV3", WrapperNamespace="http://producao.issfortaleza.com.br", IsWrapped=true)]
    public partial class RecepcionarLoteRpsV3
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Cabecalho;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string EnviarLoteRpsEnvio;
        
        public RecepcionarLoteRpsV3()
        {
        }
        
        public RecepcionarLoteRpsV3(string Cabecalho, string EnviarLoteRpsEnvio)
        {
            this.Cabecalho = Cabecalho;
            this.EnviarLoteRpsEnvio = EnviarLoteRpsEnvio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RecepcionarLoteRpsV3Response", WrapperNamespace="http://producao.issfortaleza.com.br", IsWrapped=true)]
    public partial class RecepcionarLoteRpsV3Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string EnviarLoteRpsResposta;
        
        public RecepcionarLoteRpsV3Response()
        {
        }
        
        public RecepcionarLoteRpsV3Response(string EnviarLoteRpsResposta)
        {
            this.EnviarLoteRpsResposta = EnviarLoteRpsResposta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarLoteRpsV3", WrapperNamespace="http://producao.issfortaleza.com.br", IsWrapped=true)]
    public partial class ConsultarLoteRpsV3
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Cabecalho;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string ConsultarLoteRpsEnvio;
        
        public ConsultarLoteRpsV3()
        {
        }
        
        public ConsultarLoteRpsV3(string Cabecalho, string ConsultarLoteRpsEnvio)
        {
            this.Cabecalho = Cabecalho;
            this.ConsultarLoteRpsEnvio = ConsultarLoteRpsEnvio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarLoteRpsV3Response", WrapperNamespace="http://producao.issfortaleza.com.br", IsWrapped=true)]
    public partial class ConsultarLoteRpsV3Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string ConsultarLoteRpsResposta;
        
        public ConsultarLoteRpsV3Response()
        {
        }
        
        public ConsultarLoteRpsV3Response(string ConsultarLoteRpsResposta)
        {
            this.ConsultarLoteRpsResposta = ConsultarLoteRpsResposta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarNfsePorRpsV3", WrapperNamespace="http://producao.issfortaleza.com.br", IsWrapped=true)]
    public partial class ConsultarNfsePorRpsV3
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Cabecalho;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string ConsultarNfseRpsEnvio;
        
        public ConsultarNfsePorRpsV3()
        {
        }
        
        public ConsultarNfsePorRpsV3(string Cabecalho, string ConsultarNfseRpsEnvio)
        {
            this.Cabecalho = Cabecalho;
            this.ConsultarNfseRpsEnvio = ConsultarNfseRpsEnvio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarNfsePorRpsV3Response", WrapperNamespace="http://producao.issfortaleza.com.br", IsWrapped=true)]
    public partial class ConsultarNfsePorRpsV3Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string ConsultarNfseRpsResposta;
        
        public ConsultarNfsePorRpsV3Response()
        {
        }
        
        public ConsultarNfsePorRpsV3Response(string ConsultarNfseRpsResposta)
        {
            this.ConsultarNfseRpsResposta = ConsultarNfseRpsResposta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarNfseV3", WrapperNamespace="http://producao.issfortaleza.com.br", IsWrapped=true)]
    public partial class ConsultarNfseV3
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Cabecalho;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string ConsultarNfseEnvio;
        
        public ConsultarNfseV3()
        {
        }
        
        public ConsultarNfseV3(string Cabecalho, string ConsultarNfseEnvio)
        {
            this.Cabecalho = Cabecalho;
            this.ConsultarNfseEnvio = ConsultarNfseEnvio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarNfseV3Response", WrapperNamespace="http://producao.issfortaleza.com.br", IsWrapped=true)]
    public partial class ConsultarNfseV3Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string ConsultarNfseResposta;
        
        public ConsultarNfseV3Response()
        {
        }
        
        public ConsultarNfseV3Response(string ConsultarNfseResposta)
        {
            this.ConsultarNfseResposta = ConsultarNfseResposta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarSituacaoLoteRpsV3", WrapperNamespace="http://producao.issfortaleza.com.br", IsWrapped=true)]
    public partial class ConsultarSituacaoLoteRpsV3
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Cabecalho;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string ConsultarSituacaoLoteRpsEnvio;
        
        public ConsultarSituacaoLoteRpsV3()
        {
        }
        
        public ConsultarSituacaoLoteRpsV3(string Cabecalho, string ConsultarSituacaoLoteRpsEnvio)
        {
            this.Cabecalho = Cabecalho;
            this.ConsultarSituacaoLoteRpsEnvio = ConsultarSituacaoLoteRpsEnvio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarSituacaoLoteRpsV3Response", WrapperNamespace="http://producao.issfortaleza.com.br", IsWrapped=true)]
    public partial class ConsultarSituacaoLoteRpsV3Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string ConsultarSituacaoLoteRpsResposta;
        
        public ConsultarSituacaoLoteRpsV3Response()
        {
        }
        
        public ConsultarSituacaoLoteRpsV3Response(string ConsultarSituacaoLoteRpsResposta)
        {
            this.ConsultarSituacaoLoteRpsResposta = ConsultarSituacaoLoteRpsResposta;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface ServiceGinfesChannel : ws_fortaleza.ServiceGinfes, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class ServiceGinfesClient : System.ServiceModel.ClientBase<ws_fortaleza.ServiceGinfes>, ws_fortaleza.ServiceGinfes
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceGinfesClient() : 
                base(ServiceGinfesClient.GetDefaultBinding(), ServiceGinfesClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ServiceGinfes.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceGinfesClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceGinfesClient.GetBindingForEndpoint(endpointConfiguration), ServiceGinfesClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceGinfesClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceGinfesClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceGinfesClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceGinfesClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceGinfesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ws_fortaleza.CancelarNfseResponse CancelarNfse(ws_fortaleza.CancelarNfse request)
        {
            return base.Channel.CancelarNfse(request);
        }
        
        public System.Threading.Tasks.Task<ws_fortaleza.CancelarNfseResponse> CancelarNfseAsync(ws_fortaleza.CancelarNfse request)
        {
            return base.Channel.CancelarNfseAsync(request);
        }
        
        public ws_fortaleza.RecepcionarLoteRpsV3Response RecepcionarLoteRpsV3(ws_fortaleza.RecepcionarLoteRpsV3 request)
        {
            return base.Channel.RecepcionarLoteRpsV3(request);
        }
        
        public System.Threading.Tasks.Task<ws_fortaleza.RecepcionarLoteRpsV3Response> RecepcionarLoteRpsV3Async(ws_fortaleza.RecepcionarLoteRpsV3 request)
        {
            return base.Channel.RecepcionarLoteRpsV3Async(request);
        }
        
        public ws_fortaleza.ConsultarLoteRpsV3Response ConsultarLoteRpsV3(ws_fortaleza.ConsultarLoteRpsV3 request)
        {
            return base.Channel.ConsultarLoteRpsV3(request);
        }
        
        public System.Threading.Tasks.Task<ws_fortaleza.ConsultarLoteRpsV3Response> ConsultarLoteRpsV3Async(ws_fortaleza.ConsultarLoteRpsV3 request)
        {
            return base.Channel.ConsultarLoteRpsV3Async(request);
        }
        
        public ws_fortaleza.ConsultarNfsePorRpsV3Response ConsultarNfsePorRpsV3(ws_fortaleza.ConsultarNfsePorRpsV3 request)
        {
            return base.Channel.ConsultarNfsePorRpsV3(request);
        }
        
        public System.Threading.Tasks.Task<ws_fortaleza.ConsultarNfsePorRpsV3Response> ConsultarNfsePorRpsV3Async(ws_fortaleza.ConsultarNfsePorRpsV3 request)
        {
            return base.Channel.ConsultarNfsePorRpsV3Async(request);
        }
        
        public ws_fortaleza.ConsultarNfseV3Response ConsultarNfseV3(ws_fortaleza.ConsultarNfseV3 request)
        {
            return base.Channel.ConsultarNfseV3(request);
        }
        
        public System.Threading.Tasks.Task<ws_fortaleza.ConsultarNfseV3Response> ConsultarNfseV3Async(ws_fortaleza.ConsultarNfseV3 request)
        {
            return base.Channel.ConsultarNfseV3Async(request);
        }
        
        public ws_fortaleza.ConsultarSituacaoLoteRpsV3Response ConsultarSituacaoLoteRpsV3(ws_fortaleza.ConsultarSituacaoLoteRpsV3 request)
        {
            return base.Channel.ConsultarSituacaoLoteRpsV3(request);
        }
        
        public System.Threading.Tasks.Task<ws_fortaleza.ConsultarSituacaoLoteRpsV3Response> ConsultarSituacaoLoteRpsV3Async(ws_fortaleza.ConsultarSituacaoLoteRpsV3 request)
        {
            return base.Channel.ConsultarSituacaoLoteRpsV3Async(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServiceGinfes))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServiceGinfes))
            {
                return new System.ServiceModel.EndpointAddress("https://iss.fortaleza.ce.gov.br/grpfor-iss/ServiceGinfesImplService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServiceGinfesClient.GetBindingForEndpoint(EndpointConfiguration.ServiceGinfes);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServiceGinfesClient.GetEndpointAddress(EndpointConfiguration.ServiceGinfes);
        }
        
        public enum EndpointConfiguration
        {
            
            ServiceGinfes,
        }
    }
}
