//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ws_consultas
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sped.fazenda.gov.br/", ConfigurationName="ws_consultas.ConsultasReinf")]
    public interface ConsultasReinf
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sped.fazenda.gov.br/ConsultasReinf/ConsultaResultadoFechamento2099", ReplyAction="http://sped.fazenda.gov.br/ConsultasReinf/ConsultaResultadoFechamento2099Response" +
            "")]
        ws_consultas.ConsultaResultadoFechamento2099Response ConsultaResultadoFechamento2099(ws_consultas.ConsultaResultadoFechamento2099Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sped.fazenda.gov.br/ConsultasReinf/ConsultaResultadoFechamento2099", ReplyAction="http://sped.fazenda.gov.br/ConsultasReinf/ConsultaResultadoFechamento2099Response" +
            "")]
        System.Threading.Tasks.Task<ws_consultas.ConsultaResultadoFechamento2099Response> ConsultaResultadoFechamento2099Async(ws_consultas.ConsultaResultadoFechamento2099Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sped.fazenda.gov.br/ConsultasReinf/ConsultaInformacoesConsolidadas", ReplyAction="http://sped.fazenda.gov.br/ConsultasReinf/ConsultaInformacoesConsolidadasResponse" +
            "")]
        ws_consultas.ConsultaInformacoesConsolidadasResponse ConsultaInformacoesConsolidadas(ws_consultas.ConsultaInformacoesConsolidadasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sped.fazenda.gov.br/ConsultasReinf/ConsultaInformacoesConsolidadas", ReplyAction="http://sped.fazenda.gov.br/ConsultasReinf/ConsultaInformacoesConsolidadasResponse" +
            "")]
        System.Threading.Tasks.Task<ws_consultas.ConsultaInformacoesConsolidadasResponse> ConsultaInformacoesConsolidadasAsync(ws_consultas.ConsultaInformacoesConsolidadasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sped.fazenda.gov.br/ConsultasReinf/ConsultaReciboEvento1000", ReplyAction="http://sped.fazenda.gov.br/ConsultasReinf/ConsultaReciboEvento1000Response")]
        ws_consultas.ConsultaReciboEvento1000Response ConsultaReciboEvento1000(ws_consultas.ConsultaReciboEvento1000Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sped.fazenda.gov.br/ConsultasReinf/ConsultaReciboEvento1000", ReplyAction="http://sped.fazenda.gov.br/ConsultasReinf/ConsultaReciboEvento1000Response")]
        System.Threading.Tasks.Task<ws_consultas.ConsultaReciboEvento1000Response> ConsultaReciboEvento1000Async(ws_consultas.ConsultaReciboEvento1000Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sped.fazenda.gov.br/ConsultasReinf/ConsultaReciboEvento1070", ReplyAction="http://sped.fazenda.gov.br/ConsultasReinf/ConsultaReciboEvento1070Response")]
        ws_consultas.ConsultaReciboEvento1070Response ConsultaReciboEvento1070(ws_consultas.ConsultaReciboEvento1070Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sped.fazenda.gov.br/ConsultasReinf/ConsultaReciboEvento1070", ReplyAction="http://sped.fazenda.gov.br/ConsultasReinf/ConsultaReciboEvento1070Response")]
        System.Threading.Tasks.Task<ws_consultas.ConsultaReciboEvento1070Response> ConsultaReciboEvento1070Async(ws_consultas.ConsultaReciboEvento1070Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sped.fazenda.gov.br/ConsultasReinf/ConsultaReciboEvento2010", ReplyAction="http://sped.fazenda.gov.br/ConsultasReinf/ConsultaReciboEvento2010Response")]
        ws_consultas.ConsultaReciboEvento2010Response ConsultaReciboEvento2010(ws_consultas.ConsultaReciboEvento2010Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sped.fazenda.gov.br/ConsultasReinf/ConsultaReciboEvento2010", ReplyAction="http://sped.fazenda.gov.br/ConsultasReinf/ConsultaReciboEvento2010Response")]
        System.Threading.Tasks.Task<ws_consultas.ConsultaReciboEvento2010Response> ConsultaReciboEvento2010Async(ws_consultas.ConsultaReciboEvento2010Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sped.fazenda.gov.br/ConsultasReinf/ConsultaReciboEvento2020", ReplyAction="http://sped.fazenda.gov.br/ConsultasReinf/ConsultaReciboEvento2020Response")]
        ws_consultas.ConsultaReciboEvento2020Response ConsultaReciboEvento2020(ws_consultas.ConsultaReciboEvento2020Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sped.fazenda.gov.br/ConsultasReinf/ConsultaReciboEvento2020", ReplyAction="http://sped.fazenda.gov.br/ConsultasReinf/ConsultaReciboEvento2020Response")]
        System.Threading.Tasks.Task<ws_consultas.ConsultaReciboEvento2020Response> ConsultaReciboEvento2020Async(ws_consultas.ConsultaReciboEvento2020Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sped.fazenda.gov.br/ConsultasReinf/ConsultaReciboEvento2030", ReplyAction="http://sped.fazenda.gov.br/ConsultasReinf/ConsultaReciboEvento2030Response")]
        ws_consultas.ConsultaReciboEvento2030Response ConsultaReciboEvento2030(ws_consultas.ConsultaReciboEvento2030Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sped.fazenda.gov.br/ConsultasReinf/ConsultaReciboEvento2030", ReplyAction="http://sped.fazenda.gov.br/ConsultasReinf/ConsultaReciboEvento2030Response")]
        System.Threading.Tasks.Task<ws_consultas.ConsultaReciboEvento2030Response> ConsultaReciboEvento2030Async(ws_consultas.ConsultaReciboEvento2030Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sped.fazenda.gov.br/ConsultasReinf/ConsultaReciboEvento2040", ReplyAction="http://sped.fazenda.gov.br/ConsultasReinf/ConsultaReciboEvento2040Response")]
        ws_consultas.ConsultaReciboEvento2040Response ConsultaReciboEvento2040(ws_consultas.ConsultaReciboEvento2040Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sped.fazenda.gov.br/ConsultasReinf/ConsultaReciboEvento2040", ReplyAction="http://sped.fazenda.gov.br/ConsultasReinf/ConsultaReciboEvento2040Response")]
        System.Threading.Tasks.Task<ws_consultas.ConsultaReciboEvento2040Response> ConsultaReciboEvento2040Async(ws_consultas.ConsultaReciboEvento2040Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sped.fazenda.gov.br/ConsultasReinf/ConsultaReciboEvento2050", ReplyAction="http://sped.fazenda.gov.br/ConsultasReinf/ConsultaReciboEvento2050Response")]
        ws_consultas.ConsultaReciboEvento2050Response ConsultaReciboEvento2050(ws_consultas.ConsultaReciboEvento2050Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sped.fazenda.gov.br/ConsultasReinf/ConsultaReciboEvento2050", ReplyAction="http://sped.fazenda.gov.br/ConsultasReinf/ConsultaReciboEvento2050Response")]
        System.Threading.Tasks.Task<ws_consultas.ConsultaReciboEvento2050Response> ConsultaReciboEvento2050Async(ws_consultas.ConsultaReciboEvento2050Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sped.fazenda.gov.br/ConsultasReinf/ConsultaReciboEvento2055", ReplyAction="http://sped.fazenda.gov.br/ConsultasReinf/ConsultaReciboEvento2055Response")]
        ws_consultas.ConsultaReciboEvento2055Response ConsultaReciboEvento2055(ws_consultas.ConsultaReciboEvento2055Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sped.fazenda.gov.br/ConsultasReinf/ConsultaReciboEvento2055", ReplyAction="http://sped.fazenda.gov.br/ConsultasReinf/ConsultaReciboEvento2055Response")]
        System.Threading.Tasks.Task<ws_consultas.ConsultaReciboEvento2055Response> ConsultaReciboEvento2055Async(ws_consultas.ConsultaReciboEvento2055Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sped.fazenda.gov.br/ConsultasReinf/ConsultaReciboEvento2060", ReplyAction="http://sped.fazenda.gov.br/ConsultasReinf/ConsultaReciboEvento2060Response")]
        ws_consultas.ConsultaReciboEvento2060Response ConsultaReciboEvento2060(ws_consultas.ConsultaReciboEvento2060Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sped.fazenda.gov.br/ConsultasReinf/ConsultaReciboEvento2060", ReplyAction="http://sped.fazenda.gov.br/ConsultasReinf/ConsultaReciboEvento2060Response")]
        System.Threading.Tasks.Task<ws_consultas.ConsultaReciboEvento2060Response> ConsultaReciboEvento2060Async(ws_consultas.ConsultaReciboEvento2060Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sped.fazenda.gov.br/ConsultasReinf/ConsultaReciboEvento2098", ReplyAction="http://sped.fazenda.gov.br/ConsultasReinf/ConsultaReciboEvento2098Response")]
        ws_consultas.ConsultaReciboEvento2098Response ConsultaReciboEvento2098(ws_consultas.ConsultaReciboEvento2098Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sped.fazenda.gov.br/ConsultasReinf/ConsultaReciboEvento2098", ReplyAction="http://sped.fazenda.gov.br/ConsultasReinf/ConsultaReciboEvento2098Response")]
        System.Threading.Tasks.Task<ws_consultas.ConsultaReciboEvento2098Response> ConsultaReciboEvento2098Async(ws_consultas.ConsultaReciboEvento2098Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sped.fazenda.gov.br/ConsultasReinf/ConsultaReciboEvento2099", ReplyAction="http://sped.fazenda.gov.br/ConsultasReinf/ConsultaReciboEvento2099Response")]
        ws_consultas.ConsultaReciboEvento2099Response ConsultaReciboEvento2099(ws_consultas.ConsultaReciboEvento2099Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sped.fazenda.gov.br/ConsultasReinf/ConsultaReciboEvento2099", ReplyAction="http://sped.fazenda.gov.br/ConsultasReinf/ConsultaReciboEvento2099Response")]
        System.Threading.Tasks.Task<ws_consultas.ConsultaReciboEvento2099Response> ConsultaReciboEvento2099Async(ws_consultas.ConsultaReciboEvento2099Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sped.fazenda.gov.br/ConsultasReinf/ConsultaReciboEvento3010", ReplyAction="http://sped.fazenda.gov.br/ConsultasReinf/ConsultaReciboEvento3010Response")]
        ws_consultas.ConsultaReciboEvento3010Response ConsultaReciboEvento3010(ws_consultas.ConsultaReciboEvento3010Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sped.fazenda.gov.br/ConsultasReinf/ConsultaReciboEvento3010", ReplyAction="http://sped.fazenda.gov.br/ConsultasReinf/ConsultaReciboEvento3010Response")]
        System.Threading.Tasks.Task<ws_consultas.ConsultaReciboEvento3010Response> ConsultaReciboEvento3010Async(ws_consultas.ConsultaReciboEvento3010Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaResultadoFechamento2099Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaResultadoFechamento2099", Namespace="http://sped.fazenda.gov.br/", Order=0)]
        public ws_consultas.ConsultaResultadoFechamento2099RequestBody Body;
        
        public ConsultaResultadoFechamento2099Request()
        {
        }
        
        public ConsultaResultadoFechamento2099Request(ws_consultas.ConsultaResultadoFechamento2099RequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sped.fazenda.gov.br/")]
    public partial class ConsultaResultadoFechamento2099RequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public byte tpInsc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nrInsc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string numeroProtocoloFechamento;
        
        public ConsultaResultadoFechamento2099RequestBody()
        {
        }
        
        public ConsultaResultadoFechamento2099RequestBody(byte tpInsc, string nrInsc, string numeroProtocoloFechamento)
        {
            this.tpInsc = tpInsc;
            this.nrInsc = nrInsc;
            this.numeroProtocoloFechamento = numeroProtocoloFechamento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaResultadoFechamento2099Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaResultadoFechamento2099Response", Namespace="http://sped.fazenda.gov.br/", Order=0)]
        public ws_consultas.ConsultaResultadoFechamento2099ResponseBody Body;
        
        public ConsultaResultadoFechamento2099Response()
        {
        }
        
        public ConsultaResultadoFechamento2099Response(ws_consultas.ConsultaResultadoFechamento2099ResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sped.fazenda.gov.br/")]
    public partial class ConsultaResultadoFechamento2099ResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement ConsultaResultadoFechamento2099Result;
        
        public ConsultaResultadoFechamento2099ResponseBody()
        {
        }
        
        public ConsultaResultadoFechamento2099ResponseBody(System.Xml.XmlElement ConsultaResultadoFechamento2099Result)
        {
            this.ConsultaResultadoFechamento2099Result = ConsultaResultadoFechamento2099Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaInformacoesConsolidadasRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaInformacoesConsolidadas", Namespace="http://sped.fazenda.gov.br/", Order=0)]
        public ws_consultas.ConsultaInformacoesConsolidadasRequestBody Body;
        
        public ConsultaInformacoesConsolidadasRequest()
        {
        }
        
        public ConsultaInformacoesConsolidadasRequest(ws_consultas.ConsultaInformacoesConsolidadasRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sped.fazenda.gov.br/")]
    public partial class ConsultaInformacoesConsolidadasRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public byte tipoInscricaoContribuinte;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string numeroInscricaoContribuinte;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string numeroProtocoloFechamento;
        
        public ConsultaInformacoesConsolidadasRequestBody()
        {
        }
        
        public ConsultaInformacoesConsolidadasRequestBody(byte tipoInscricaoContribuinte, string numeroInscricaoContribuinte, string numeroProtocoloFechamento)
        {
            this.tipoInscricaoContribuinte = tipoInscricaoContribuinte;
            this.numeroInscricaoContribuinte = numeroInscricaoContribuinte;
            this.numeroProtocoloFechamento = numeroProtocoloFechamento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaInformacoesConsolidadasResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaInformacoesConsolidadasResponse", Namespace="http://sped.fazenda.gov.br/", Order=0)]
        public ws_consultas.ConsultaInformacoesConsolidadasResponseBody Body;
        
        public ConsultaInformacoesConsolidadasResponse()
        {
        }
        
        public ConsultaInformacoesConsolidadasResponse(ws_consultas.ConsultaInformacoesConsolidadasResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sped.fazenda.gov.br/")]
    public partial class ConsultaInformacoesConsolidadasResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement ConsultaInformacoesConsolidadasResult;
        
        public ConsultaInformacoesConsolidadasResponseBody()
        {
        }
        
        public ConsultaInformacoesConsolidadasResponseBody(System.Xml.XmlElement ConsultaInformacoesConsolidadasResult)
        {
            this.ConsultaInformacoesConsolidadasResult = ConsultaInformacoesConsolidadasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaReciboEvento1000Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaReciboEvento1000", Namespace="http://sped.fazenda.gov.br/", Order=0)]
        public ws_consultas.ConsultaReciboEvento1000RequestBody Body;
        
        public ConsultaReciboEvento1000Request()
        {
        }
        
        public ConsultaReciboEvento1000Request(ws_consultas.ConsultaReciboEvento1000RequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sped.fazenda.gov.br/")]
    public partial class ConsultaReciboEvento1000RequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int tipoEvento;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public byte tpInsc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nrInsc;
        
        public ConsultaReciboEvento1000RequestBody()
        {
        }
        
        public ConsultaReciboEvento1000RequestBody(int tipoEvento, byte tpInsc, string nrInsc)
        {
            this.tipoEvento = tipoEvento;
            this.tpInsc = tpInsc;
            this.nrInsc = nrInsc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaReciboEvento1000Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaReciboEvento1000Response", Namespace="http://sped.fazenda.gov.br/", Order=0)]
        public ws_consultas.ConsultaReciboEvento1000ResponseBody Body;
        
        public ConsultaReciboEvento1000Response()
        {
        }
        
        public ConsultaReciboEvento1000Response(ws_consultas.ConsultaReciboEvento1000ResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sped.fazenda.gov.br/")]
    public partial class ConsultaReciboEvento1000ResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement ConsultaReciboEvento1000Result;
        
        public ConsultaReciboEvento1000ResponseBody()
        {
        }
        
        public ConsultaReciboEvento1000ResponseBody(System.Xml.XmlElement ConsultaReciboEvento1000Result)
        {
            this.ConsultaReciboEvento1000Result = ConsultaReciboEvento1000Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaReciboEvento1070Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaReciboEvento1070", Namespace="http://sped.fazenda.gov.br/", Order=0)]
        public ws_consultas.ConsultaReciboEvento1070RequestBody Body;
        
        public ConsultaReciboEvento1070Request()
        {
        }
        
        public ConsultaReciboEvento1070Request(ws_consultas.ConsultaReciboEvento1070RequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sped.fazenda.gov.br/")]
    public partial class ConsultaReciboEvento1070RequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int tipoEvento;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public byte tpInsc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nrInsc;
        
        public ConsultaReciboEvento1070RequestBody()
        {
        }
        
        public ConsultaReciboEvento1070RequestBody(int tipoEvento, byte tpInsc, string nrInsc)
        {
            this.tipoEvento = tipoEvento;
            this.tpInsc = tpInsc;
            this.nrInsc = nrInsc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaReciboEvento1070Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaReciboEvento1070Response", Namespace="http://sped.fazenda.gov.br/", Order=0)]
        public ws_consultas.ConsultaReciboEvento1070ResponseBody Body;
        
        public ConsultaReciboEvento1070Response()
        {
        }
        
        public ConsultaReciboEvento1070Response(ws_consultas.ConsultaReciboEvento1070ResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sped.fazenda.gov.br/")]
    public partial class ConsultaReciboEvento1070ResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement ConsultaReciboEvento1070Result;
        
        public ConsultaReciboEvento1070ResponseBody()
        {
        }
        
        public ConsultaReciboEvento1070ResponseBody(System.Xml.XmlElement ConsultaReciboEvento1070Result)
        {
            this.ConsultaReciboEvento1070Result = ConsultaReciboEvento1070Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaReciboEvento2010Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaReciboEvento2010", Namespace="http://sped.fazenda.gov.br/", Order=0)]
        public ws_consultas.ConsultaReciboEvento2010RequestBody Body;
        
        public ConsultaReciboEvento2010Request()
        {
        }
        
        public ConsultaReciboEvento2010Request(ws_consultas.ConsultaReciboEvento2010RequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sped.fazenda.gov.br/")]
    public partial class ConsultaReciboEvento2010RequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int tipoEvento;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public byte tpInsc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nrInsc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string perApur;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public byte tpInscEstab;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string nrInscEstab;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string cnpjPrestador;
        
        public ConsultaReciboEvento2010RequestBody()
        {
        }
        
        public ConsultaReciboEvento2010RequestBody(int tipoEvento, byte tpInsc, string nrInsc, string perApur, byte tpInscEstab, string nrInscEstab, string cnpjPrestador)
        {
            this.tipoEvento = tipoEvento;
            this.tpInsc = tpInsc;
            this.nrInsc = nrInsc;
            this.perApur = perApur;
            this.tpInscEstab = tpInscEstab;
            this.nrInscEstab = nrInscEstab;
            this.cnpjPrestador = cnpjPrestador;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaReciboEvento2010Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaReciboEvento2010Response", Namespace="http://sped.fazenda.gov.br/", Order=0)]
        public ws_consultas.ConsultaReciboEvento2010ResponseBody Body;
        
        public ConsultaReciboEvento2010Response()
        {
        }
        
        public ConsultaReciboEvento2010Response(ws_consultas.ConsultaReciboEvento2010ResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sped.fazenda.gov.br/")]
    public partial class ConsultaReciboEvento2010ResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement ConsultaReciboEvento2010Result;
        
        public ConsultaReciboEvento2010ResponseBody()
        {
        }
        
        public ConsultaReciboEvento2010ResponseBody(System.Xml.XmlElement ConsultaReciboEvento2010Result)
        {
            this.ConsultaReciboEvento2010Result = ConsultaReciboEvento2010Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaReciboEvento2020Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaReciboEvento2020", Namespace="http://sped.fazenda.gov.br/", Order=0)]
        public ws_consultas.ConsultaReciboEvento2020RequestBody Body;
        
        public ConsultaReciboEvento2020Request()
        {
        }
        
        public ConsultaReciboEvento2020Request(ws_consultas.ConsultaReciboEvento2020RequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sped.fazenda.gov.br/")]
    public partial class ConsultaReciboEvento2020RequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int tipoEvento;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public byte tpInsc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nrInsc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string perApur;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string nrInscEstabPrest;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public byte tpInscTomador;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string nrInscTomador;
        
        public ConsultaReciboEvento2020RequestBody()
        {
        }
        
        public ConsultaReciboEvento2020RequestBody(int tipoEvento, byte tpInsc, string nrInsc, string perApur, string nrInscEstabPrest, byte tpInscTomador, string nrInscTomador)
        {
            this.tipoEvento = tipoEvento;
            this.tpInsc = tpInsc;
            this.nrInsc = nrInsc;
            this.perApur = perApur;
            this.nrInscEstabPrest = nrInscEstabPrest;
            this.tpInscTomador = tpInscTomador;
            this.nrInscTomador = nrInscTomador;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaReciboEvento2020Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaReciboEvento2020Response", Namespace="http://sped.fazenda.gov.br/", Order=0)]
        public ws_consultas.ConsultaReciboEvento2020ResponseBody Body;
        
        public ConsultaReciboEvento2020Response()
        {
        }
        
        public ConsultaReciboEvento2020Response(ws_consultas.ConsultaReciboEvento2020ResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sped.fazenda.gov.br/")]
    public partial class ConsultaReciboEvento2020ResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement ConsultaReciboEvento2020Result;
        
        public ConsultaReciboEvento2020ResponseBody()
        {
        }
        
        public ConsultaReciboEvento2020ResponseBody(System.Xml.XmlElement ConsultaReciboEvento2020Result)
        {
            this.ConsultaReciboEvento2020Result = ConsultaReciboEvento2020Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaReciboEvento2030Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaReciboEvento2030", Namespace="http://sped.fazenda.gov.br/", Order=0)]
        public ws_consultas.ConsultaReciboEvento2030RequestBody Body;
        
        public ConsultaReciboEvento2030Request()
        {
        }
        
        public ConsultaReciboEvento2030Request(ws_consultas.ConsultaReciboEvento2030RequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sped.fazenda.gov.br/")]
    public partial class ConsultaReciboEvento2030RequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int tipoEvento;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public byte tpInsc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nrInsc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string perApur;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string nrInscEstab;
        
        public ConsultaReciboEvento2030RequestBody()
        {
        }
        
        public ConsultaReciboEvento2030RequestBody(int tipoEvento, byte tpInsc, string nrInsc, string perApur, string nrInscEstab)
        {
            this.tipoEvento = tipoEvento;
            this.tpInsc = tpInsc;
            this.nrInsc = nrInsc;
            this.perApur = perApur;
            this.nrInscEstab = nrInscEstab;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaReciboEvento2030Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaReciboEvento2030Response", Namespace="http://sped.fazenda.gov.br/", Order=0)]
        public ws_consultas.ConsultaReciboEvento2030ResponseBody Body;
        
        public ConsultaReciboEvento2030Response()
        {
        }
        
        public ConsultaReciboEvento2030Response(ws_consultas.ConsultaReciboEvento2030ResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sped.fazenda.gov.br/")]
    public partial class ConsultaReciboEvento2030ResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement ConsultaReciboEvento2030Result;
        
        public ConsultaReciboEvento2030ResponseBody()
        {
        }
        
        public ConsultaReciboEvento2030ResponseBody(System.Xml.XmlElement ConsultaReciboEvento2030Result)
        {
            this.ConsultaReciboEvento2030Result = ConsultaReciboEvento2030Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaReciboEvento2040Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaReciboEvento2040", Namespace="http://sped.fazenda.gov.br/", Order=0)]
        public ws_consultas.ConsultaReciboEvento2040RequestBody Body;
        
        public ConsultaReciboEvento2040Request()
        {
        }
        
        public ConsultaReciboEvento2040Request(ws_consultas.ConsultaReciboEvento2040RequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sped.fazenda.gov.br/")]
    public partial class ConsultaReciboEvento2040RequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int tipoEvento;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public byte tpInsc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nrInsc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string perApur;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string nrInscEstab;
        
        public ConsultaReciboEvento2040RequestBody()
        {
        }
        
        public ConsultaReciboEvento2040RequestBody(int tipoEvento, byte tpInsc, string nrInsc, string perApur, string nrInscEstab)
        {
            this.tipoEvento = tipoEvento;
            this.tpInsc = tpInsc;
            this.nrInsc = nrInsc;
            this.perApur = perApur;
            this.nrInscEstab = nrInscEstab;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaReciboEvento2040Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaReciboEvento2040Response", Namespace="http://sped.fazenda.gov.br/", Order=0)]
        public ws_consultas.ConsultaReciboEvento2040ResponseBody Body;
        
        public ConsultaReciboEvento2040Response()
        {
        }
        
        public ConsultaReciboEvento2040Response(ws_consultas.ConsultaReciboEvento2040ResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sped.fazenda.gov.br/")]
    public partial class ConsultaReciboEvento2040ResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement ConsultaReciboEvento2040Result;
        
        public ConsultaReciboEvento2040ResponseBody()
        {
        }
        
        public ConsultaReciboEvento2040ResponseBody(System.Xml.XmlElement ConsultaReciboEvento2040Result)
        {
            this.ConsultaReciboEvento2040Result = ConsultaReciboEvento2040Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaReciboEvento2050Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaReciboEvento2050", Namespace="http://sped.fazenda.gov.br/", Order=0)]
        public ws_consultas.ConsultaReciboEvento2050RequestBody Body;
        
        public ConsultaReciboEvento2050Request()
        {
        }
        
        public ConsultaReciboEvento2050Request(ws_consultas.ConsultaReciboEvento2050RequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sped.fazenda.gov.br/")]
    public partial class ConsultaReciboEvento2050RequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int tipoEvento;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public byte tpInsc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nrInsc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string perApur;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string nrInscEstab;
        
        public ConsultaReciboEvento2050RequestBody()
        {
        }
        
        public ConsultaReciboEvento2050RequestBody(int tipoEvento, byte tpInsc, string nrInsc, string perApur, string nrInscEstab)
        {
            this.tipoEvento = tipoEvento;
            this.tpInsc = tpInsc;
            this.nrInsc = nrInsc;
            this.perApur = perApur;
            this.nrInscEstab = nrInscEstab;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaReciboEvento2050Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaReciboEvento2050Response", Namespace="http://sped.fazenda.gov.br/", Order=0)]
        public ws_consultas.ConsultaReciboEvento2050ResponseBody Body;
        
        public ConsultaReciboEvento2050Response()
        {
        }
        
        public ConsultaReciboEvento2050Response(ws_consultas.ConsultaReciboEvento2050ResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sped.fazenda.gov.br/")]
    public partial class ConsultaReciboEvento2050ResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement ConsultaReciboEvento2050Result;
        
        public ConsultaReciboEvento2050ResponseBody()
        {
        }
        
        public ConsultaReciboEvento2050ResponseBody(System.Xml.XmlElement ConsultaReciboEvento2050Result)
        {
            this.ConsultaReciboEvento2050Result = ConsultaReciboEvento2050Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaReciboEvento2055Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaReciboEvento2055", Namespace="http://sped.fazenda.gov.br/", Order=0)]
        public ws_consultas.ConsultaReciboEvento2055RequestBody Body;
        
        public ConsultaReciboEvento2055Request()
        {
        }
        
        public ConsultaReciboEvento2055Request(ws_consultas.ConsultaReciboEvento2055RequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sped.fazenda.gov.br/")]
    public partial class ConsultaReciboEvento2055RequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int tipoEvento;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public byte tpInsc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nrInsc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string perApur;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public byte tpInscAdq;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string nrInscAdq;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public byte tpInscProd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string nrInscProd;
        
        public ConsultaReciboEvento2055RequestBody()
        {
        }
        
        public ConsultaReciboEvento2055RequestBody(int tipoEvento, byte tpInsc, string nrInsc, string perApur, byte tpInscAdq, string nrInscAdq, byte tpInscProd, string nrInscProd)
        {
            this.tipoEvento = tipoEvento;
            this.tpInsc = tpInsc;
            this.nrInsc = nrInsc;
            this.perApur = perApur;
            this.tpInscAdq = tpInscAdq;
            this.nrInscAdq = nrInscAdq;
            this.tpInscProd = tpInscProd;
            this.nrInscProd = nrInscProd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaReciboEvento2055Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaReciboEvento2055Response", Namespace="http://sped.fazenda.gov.br/", Order=0)]
        public ws_consultas.ConsultaReciboEvento2055ResponseBody Body;
        
        public ConsultaReciboEvento2055Response()
        {
        }
        
        public ConsultaReciboEvento2055Response(ws_consultas.ConsultaReciboEvento2055ResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sped.fazenda.gov.br/")]
    public partial class ConsultaReciboEvento2055ResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement ConsultaReciboEvento2055Result;
        
        public ConsultaReciboEvento2055ResponseBody()
        {
        }
        
        public ConsultaReciboEvento2055ResponseBody(System.Xml.XmlElement ConsultaReciboEvento2055Result)
        {
            this.ConsultaReciboEvento2055Result = ConsultaReciboEvento2055Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaReciboEvento2060Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaReciboEvento2060", Namespace="http://sped.fazenda.gov.br/", Order=0)]
        public ws_consultas.ConsultaReciboEvento2060RequestBody Body;
        
        public ConsultaReciboEvento2060Request()
        {
        }
        
        public ConsultaReciboEvento2060Request(ws_consultas.ConsultaReciboEvento2060RequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sped.fazenda.gov.br/")]
    public partial class ConsultaReciboEvento2060RequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int tipoEvento;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public byte tpInsc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nrInsc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string perApur;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public byte tpInscEstab;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string nrInscEstab;
        
        public ConsultaReciboEvento2060RequestBody()
        {
        }
        
        public ConsultaReciboEvento2060RequestBody(int tipoEvento, byte tpInsc, string nrInsc, string perApur, byte tpInscEstab, string nrInscEstab)
        {
            this.tipoEvento = tipoEvento;
            this.tpInsc = tpInsc;
            this.nrInsc = nrInsc;
            this.perApur = perApur;
            this.tpInscEstab = tpInscEstab;
            this.nrInscEstab = nrInscEstab;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaReciboEvento2060Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaReciboEvento2060Response", Namespace="http://sped.fazenda.gov.br/", Order=0)]
        public ws_consultas.ConsultaReciboEvento2060ResponseBody Body;
        
        public ConsultaReciboEvento2060Response()
        {
        }
        
        public ConsultaReciboEvento2060Response(ws_consultas.ConsultaReciboEvento2060ResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sped.fazenda.gov.br/")]
    public partial class ConsultaReciboEvento2060ResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement ConsultaReciboEvento2060Result;
        
        public ConsultaReciboEvento2060ResponseBody()
        {
        }
        
        public ConsultaReciboEvento2060ResponseBody(System.Xml.XmlElement ConsultaReciboEvento2060Result)
        {
            this.ConsultaReciboEvento2060Result = ConsultaReciboEvento2060Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaReciboEvento2098Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaReciboEvento2098", Namespace="http://sped.fazenda.gov.br/", Order=0)]
        public ws_consultas.ConsultaReciboEvento2098RequestBody Body;
        
        public ConsultaReciboEvento2098Request()
        {
        }
        
        public ConsultaReciboEvento2098Request(ws_consultas.ConsultaReciboEvento2098RequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sped.fazenda.gov.br/")]
    public partial class ConsultaReciboEvento2098RequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int tipoEvento;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public byte tpInsc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nrInsc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string perApur;
        
        public ConsultaReciboEvento2098RequestBody()
        {
        }
        
        public ConsultaReciboEvento2098RequestBody(int tipoEvento, byte tpInsc, string nrInsc, string perApur)
        {
            this.tipoEvento = tipoEvento;
            this.tpInsc = tpInsc;
            this.nrInsc = nrInsc;
            this.perApur = perApur;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaReciboEvento2098Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaReciboEvento2098Response", Namespace="http://sped.fazenda.gov.br/", Order=0)]
        public ws_consultas.ConsultaReciboEvento2098ResponseBody Body;
        
        public ConsultaReciboEvento2098Response()
        {
        }
        
        public ConsultaReciboEvento2098Response(ws_consultas.ConsultaReciboEvento2098ResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sped.fazenda.gov.br/")]
    public partial class ConsultaReciboEvento2098ResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement ConsultaReciboEvento2098Result;
        
        public ConsultaReciboEvento2098ResponseBody()
        {
        }
        
        public ConsultaReciboEvento2098ResponseBody(System.Xml.XmlElement ConsultaReciboEvento2098Result)
        {
            this.ConsultaReciboEvento2098Result = ConsultaReciboEvento2098Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaReciboEvento2099Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaReciboEvento2099", Namespace="http://sped.fazenda.gov.br/", Order=0)]
        public ws_consultas.ConsultaReciboEvento2099RequestBody Body;
        
        public ConsultaReciboEvento2099Request()
        {
        }
        
        public ConsultaReciboEvento2099Request(ws_consultas.ConsultaReciboEvento2099RequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sped.fazenda.gov.br/")]
    public partial class ConsultaReciboEvento2099RequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int tipoEvento;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public byte tpInsc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nrInsc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string perApur;
        
        public ConsultaReciboEvento2099RequestBody()
        {
        }
        
        public ConsultaReciboEvento2099RequestBody(int tipoEvento, byte tpInsc, string nrInsc, string perApur)
        {
            this.tipoEvento = tipoEvento;
            this.tpInsc = tpInsc;
            this.nrInsc = nrInsc;
            this.perApur = perApur;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaReciboEvento2099Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaReciboEvento2099Response", Namespace="http://sped.fazenda.gov.br/", Order=0)]
        public ws_consultas.ConsultaReciboEvento2099ResponseBody Body;
        
        public ConsultaReciboEvento2099Response()
        {
        }
        
        public ConsultaReciboEvento2099Response(ws_consultas.ConsultaReciboEvento2099ResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sped.fazenda.gov.br/")]
    public partial class ConsultaReciboEvento2099ResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement ConsultaReciboEvento2099Result;
        
        public ConsultaReciboEvento2099ResponseBody()
        {
        }
        
        public ConsultaReciboEvento2099ResponseBody(System.Xml.XmlElement ConsultaReciboEvento2099Result)
        {
            this.ConsultaReciboEvento2099Result = ConsultaReciboEvento2099Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaReciboEvento3010Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaReciboEvento3010", Namespace="http://sped.fazenda.gov.br/", Order=0)]
        public ws_consultas.ConsultaReciboEvento3010RequestBody Body;
        
        public ConsultaReciboEvento3010Request()
        {
        }
        
        public ConsultaReciboEvento3010Request(ws_consultas.ConsultaReciboEvento3010RequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sped.fazenda.gov.br/")]
    public partial class ConsultaReciboEvento3010RequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int tipoEvento;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public byte tpInsc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nrInsc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string dtApur;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string nrInscEstabelecimento;
        
        public ConsultaReciboEvento3010RequestBody()
        {
        }
        
        public ConsultaReciboEvento3010RequestBody(int tipoEvento, byte tpInsc, string nrInsc, string dtApur, string nrInscEstabelecimento)
        {
            this.tipoEvento = tipoEvento;
            this.tpInsc = tpInsc;
            this.nrInsc = nrInsc;
            this.dtApur = dtApur;
            this.nrInscEstabelecimento = nrInscEstabelecimento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaReciboEvento3010Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaReciboEvento3010Response", Namespace="http://sped.fazenda.gov.br/", Order=0)]
        public ws_consultas.ConsultaReciboEvento3010ResponseBody Body;
        
        public ConsultaReciboEvento3010Response()
        {
        }
        
        public ConsultaReciboEvento3010Response(ws_consultas.ConsultaReciboEvento3010ResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sped.fazenda.gov.br/")]
    public partial class ConsultaReciboEvento3010ResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement ConsultaReciboEvento3010Result;
        
        public ConsultaReciboEvento3010ResponseBody()
        {
        }
        
        public ConsultaReciboEvento3010ResponseBody(System.Xml.XmlElement ConsultaReciboEvento3010Result)
        {
            this.ConsultaReciboEvento3010Result = ConsultaReciboEvento3010Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface ConsultasReinfChannel : ws_consultas.ConsultasReinf, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class ConsultasReinfClient : System.ServiceModel.ClientBase<ws_consultas.ConsultasReinf>, ws_consultas.ConsultasReinf
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ConsultasReinfClient() : 
                base(ConsultasReinfClient.GetDefaultBinding(), ConsultasReinfClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ConsultasReinf.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ConsultasReinfClient(EndpointConfiguration endpointConfiguration) : 
                base(ConsultasReinfClient.GetBindingForEndpoint(endpointConfiguration), ConsultasReinfClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ConsultasReinfClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ConsultasReinfClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ConsultasReinfClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ConsultasReinfClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ConsultasReinfClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ws_consultas.ConsultaResultadoFechamento2099Response ConsultaResultadoFechamento2099(ws_consultas.ConsultaResultadoFechamento2099Request request)
        {
            return base.Channel.ConsultaResultadoFechamento2099(request);
        }
        
        public System.Threading.Tasks.Task<ws_consultas.ConsultaResultadoFechamento2099Response> ConsultaResultadoFechamento2099Async(ws_consultas.ConsultaResultadoFechamento2099Request request)
        {
            return base.Channel.ConsultaResultadoFechamento2099Async(request);
        }
        
        public ws_consultas.ConsultaInformacoesConsolidadasResponse ConsultaInformacoesConsolidadas(ws_consultas.ConsultaInformacoesConsolidadasRequest request)
        {
            return base.Channel.ConsultaInformacoesConsolidadas(request);
        }
        
        public System.Threading.Tasks.Task<ws_consultas.ConsultaInformacoesConsolidadasResponse> ConsultaInformacoesConsolidadasAsync(ws_consultas.ConsultaInformacoesConsolidadasRequest request)
        {
            return base.Channel.ConsultaInformacoesConsolidadasAsync(request);
        }
        
        public ws_consultas.ConsultaReciboEvento1000Response ConsultaReciboEvento1000(ws_consultas.ConsultaReciboEvento1000Request request)
        {
            return base.Channel.ConsultaReciboEvento1000(request);
        }
        
        public System.Threading.Tasks.Task<ws_consultas.ConsultaReciboEvento1000Response> ConsultaReciboEvento1000Async(ws_consultas.ConsultaReciboEvento1000Request request)
        {
            return base.Channel.ConsultaReciboEvento1000Async(request);
        }
        
        public ws_consultas.ConsultaReciboEvento1070Response ConsultaReciboEvento1070(ws_consultas.ConsultaReciboEvento1070Request request)
        {
            return base.Channel.ConsultaReciboEvento1070(request);
        }
        
        public System.Threading.Tasks.Task<ws_consultas.ConsultaReciboEvento1070Response> ConsultaReciboEvento1070Async(ws_consultas.ConsultaReciboEvento1070Request request)
        {
            return base.Channel.ConsultaReciboEvento1070Async(request);
        }
        
        public ws_consultas.ConsultaReciboEvento2010Response ConsultaReciboEvento2010(ws_consultas.ConsultaReciboEvento2010Request request)
        {
            return base.Channel.ConsultaReciboEvento2010(request);
        }
        
        public System.Threading.Tasks.Task<ws_consultas.ConsultaReciboEvento2010Response> ConsultaReciboEvento2010Async(ws_consultas.ConsultaReciboEvento2010Request request)
        {
            return base.Channel.ConsultaReciboEvento2010Async(request);
        }
        
        public ws_consultas.ConsultaReciboEvento2020Response ConsultaReciboEvento2020(ws_consultas.ConsultaReciboEvento2020Request request)
        {
            return base.Channel.ConsultaReciboEvento2020(request);
        }
        
        public System.Threading.Tasks.Task<ws_consultas.ConsultaReciboEvento2020Response> ConsultaReciboEvento2020Async(ws_consultas.ConsultaReciboEvento2020Request request)
        {
            return base.Channel.ConsultaReciboEvento2020Async(request);
        }
        
        public ws_consultas.ConsultaReciboEvento2030Response ConsultaReciboEvento2030(ws_consultas.ConsultaReciboEvento2030Request request)
        {
            return base.Channel.ConsultaReciboEvento2030(request);
        }
        
        public System.Threading.Tasks.Task<ws_consultas.ConsultaReciboEvento2030Response> ConsultaReciboEvento2030Async(ws_consultas.ConsultaReciboEvento2030Request request)
        {
            return base.Channel.ConsultaReciboEvento2030Async(request);
        }
        
        public ws_consultas.ConsultaReciboEvento2040Response ConsultaReciboEvento2040(ws_consultas.ConsultaReciboEvento2040Request request)
        {
            return base.Channel.ConsultaReciboEvento2040(request);
        }
        
        public System.Threading.Tasks.Task<ws_consultas.ConsultaReciboEvento2040Response> ConsultaReciboEvento2040Async(ws_consultas.ConsultaReciboEvento2040Request request)
        {
            return base.Channel.ConsultaReciboEvento2040Async(request);
        }
        
        public ws_consultas.ConsultaReciboEvento2050Response ConsultaReciboEvento2050(ws_consultas.ConsultaReciboEvento2050Request request)
        {
            return base.Channel.ConsultaReciboEvento2050(request);
        }
        
        public System.Threading.Tasks.Task<ws_consultas.ConsultaReciboEvento2050Response> ConsultaReciboEvento2050Async(ws_consultas.ConsultaReciboEvento2050Request request)
        {
            return base.Channel.ConsultaReciboEvento2050Async(request);
        }
        
        public ws_consultas.ConsultaReciboEvento2055Response ConsultaReciboEvento2055(ws_consultas.ConsultaReciboEvento2055Request request)
        {
            return base.Channel.ConsultaReciboEvento2055(request);
        }
        
        public System.Threading.Tasks.Task<ws_consultas.ConsultaReciboEvento2055Response> ConsultaReciboEvento2055Async(ws_consultas.ConsultaReciboEvento2055Request request)
        {
            return base.Channel.ConsultaReciboEvento2055Async(request);
        }
        
        public ws_consultas.ConsultaReciboEvento2060Response ConsultaReciboEvento2060(ws_consultas.ConsultaReciboEvento2060Request request)
        {
            return base.Channel.ConsultaReciboEvento2060(request);
        }
        
        public System.Threading.Tasks.Task<ws_consultas.ConsultaReciboEvento2060Response> ConsultaReciboEvento2060Async(ws_consultas.ConsultaReciboEvento2060Request request)
        {
            return base.Channel.ConsultaReciboEvento2060Async(request);
        }
        
        public ws_consultas.ConsultaReciboEvento2098Response ConsultaReciboEvento2098(ws_consultas.ConsultaReciboEvento2098Request request)
        {
            return base.Channel.ConsultaReciboEvento2098(request);
        }
        
        public System.Threading.Tasks.Task<ws_consultas.ConsultaReciboEvento2098Response> ConsultaReciboEvento2098Async(ws_consultas.ConsultaReciboEvento2098Request request)
        {
            return base.Channel.ConsultaReciboEvento2098Async(request);
        }
        
        public ws_consultas.ConsultaReciboEvento2099Response ConsultaReciboEvento2099(ws_consultas.ConsultaReciboEvento2099Request request)
        {
            return base.Channel.ConsultaReciboEvento2099(request);
        }
        
        public System.Threading.Tasks.Task<ws_consultas.ConsultaReciboEvento2099Response> ConsultaReciboEvento2099Async(ws_consultas.ConsultaReciboEvento2099Request request)
        {
            return base.Channel.ConsultaReciboEvento2099Async(request);
        }
        
        public ws_consultas.ConsultaReciboEvento3010Response ConsultaReciboEvento3010(ws_consultas.ConsultaReciboEvento3010Request request)
        {
            return base.Channel.ConsultaReciboEvento3010(request);
        }
        
        public System.Threading.Tasks.Task<ws_consultas.ConsultaReciboEvento3010Response> ConsultaReciboEvento3010Async(ws_consultas.ConsultaReciboEvento3010Request request)
        {
            return base.Channel.ConsultaReciboEvento3010Async(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ConsultasReinf))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ConsultasReinf))
            {
                return new System.ServiceModel.EndpointAddress("https://reinf.receita.fazenda.gov.br/WsREINFConsultas/ConsultasReinf.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ConsultasReinfClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ConsultasReinf);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ConsultasReinfClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ConsultasReinf);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ConsultasReinf,
        }
    }
}
